import { categoryImages } from "@/assets/images/categories";
import { CategoriesId } from "@/assets/images/categories";

export interface Video {
  video_id: string;
  title: string;
  duration: number;
  url: string;
  thumbnail: string;
  author: string;
}

export interface CategoryData {
  id: string;
  name: string;
  image?: string; // Hình ảnh cho category (optional)
  videos: Video[];
}

export const SHOW_CATEGORIES: CategoryData[] = [
  {
    id: CategoriesId.HOT_SONGS,
    image: categoryImages[CategoriesId.HOT_SONGS],
    name: "Tháng 12 Ấm Áp",
    videos: [
      {
        video_id: "IDm9AIT-GYU",
        title: "KARAOKE | Không Thời Gian - Dương Domic | Y T KALAKOLE",
        duration: 219,
        url: "https://youtube.com/watch?v=IDm9AIT-GYU",
        thumbnail: "https://i.ytimg.com/vi/IDm9AIT-GYU/hqdefault.jpg",
        author: "Y T KALAKOLE",
      },
      {
        video_id: "FZeQB3oXCa0",
        title: "Có Ai Thương Em Như Anh (#CATENA) - Tóc Tiên | Karaoke",
        duration: 232,
        url: "https://youtube.com/watch?v=FZeQB3oXCa0",
        thumbnail: "https://i.ytimg.com/vi/FZeQB3oXCa0/hq720.jpg",
        author: "SING KARA",
      },
      {
        video_id: "I-znCceSs-8",
        title:
          "KARAOKE || MIN - chẳng phải tình đầu sao đau đến thế feat. Dangrangto, Antransax (Beat Chuẩn)",
        duration: 279,
        url: "https://youtube.com/watch?v=I-znCceSs-8",
        thumbnail: "https://i.ytimg.com/vi/I-znCceSs-8/hq720.jpg",
        author: "Bản Karaoke",
      },
      {
        video_id: "ijajoDzY-2k",
        title: "Chiec Khan Gio Am Karaoke - Khanh Phuong",
        duration: 263,
        url: "https://youtube.com/watch?v=ijajoDzY-2k",
        thumbnail: "https://i.ytimg.com/vi/ijajoDzY-2k/hqdefault.jpg",
        author: "CaoCuongProKaraoke",
      },
      {
        video_id: "l3iEnBThkIc",
        title:
          "All I Want For Christmas Is You - Mariah Carey (Karaoke Songs With Lyrics - Original Key)",
        duration: 272,
        url: "https://youtube.com/watch?v=l3iEnBThkIc",
        thumbnail: "https://i.ytimg.com/vi/l3iEnBThkIc/hq720.jpg",
        author: "Musisi Karaoke",
      },
      {
        video_id: "8EJ5JRbu47Y",
        title: "Jingle Bells • Karaoke",
        duration: 153,
        url: "https://youtube.com/watch?v=8EJ5JRbu47Y",
        thumbnail: "https://i.ytimg.com/vi/8EJ5JRbu47Y/hq720.jpg",
        author: "Lugn",
      },
      {
        video_id: "gSkxv32zJqU",
        title:
          "TRỌN VẸN CHÍNH MÌNH KARAOKE - HƯƠNG GIANG x NGUYỄN VĂN CHUNG | BEAT GỐC",
        duration: 289,
        url: "https://youtube.com/watch?v=gSkxv32zJqU",
        thumbnail: "https://i.ytimg.com/vi/gSkxv32zJqU/hq720.jpg",
        author: "NVC Karaoke",
      },
      {
        video_id: "57ZJ_E0tzoA",
        title:
          "[ KARAOKE BEAT CHUẨN ] | KHÔNG THỂ CÙNG NHAU SUỐT KIẾP - HOÀ MINZY (ft. MR. SIRO)",
        duration: 301,
        url: "https://youtube.com/watch?v=57ZJ_E0tzoA",
        thumbnail: "https://i.ytimg.com/vi/57ZJ_E0tzoA/hq720.jpg",
        author: "Hòa Minzy",
      },
      {
        video_id: "RuA2l3c_bfg",
        title:
          '[KARAOKE] "Bản thiết kế" by MOPIUS | Quang Hùng Master D, Dương Domic, JSOL, HURRYKNG | BEAT GỐC',
        duration: 288,
        url: "https://youtube.com/watch?v=RuA2l3c_bfg",
        thumbnail: "https://i.ytimg.com/vi/RuA2l3c_bfg/hq720.jpg",
        author: "Tuần đi hát 3 cữ",
      },
      {
        video_id: "CVlYc2KLzkQ",
        title: "Sau Ngần Ấy Năm - Hà Nhi | Karaoke Tone Nữ",
        duration: 281,
        url: "https://youtube.com/watch?v=CVlYc2KLzkQ",
        thumbnail: "https://i.ytimg.com/vi/CVlYc2KLzkQ/hq720.jpg",
        author: "Hà Nhi Official",
      },
      {
        video_id: "vim48-F-z2w",
        title:
          "KARAOKE | Chẳng Hợp Nhau Đâu - Lê Bảo Bình  | Beat Tone Nam Chuẩn",
        duration: 305,
        url: "https://youtube.com/watch?v=vim48-F-z2w",
        thumbnail: "https://i.ytimg.com/vi/vim48-F-z2w/hq720.jpg",
        author: "ACV Karaoke",
      },
      {
        video_id: "ndLYTg_roj0",
        title: "KARAOKE BEAT CHUẨN | RỒI TA SẼ NGẮM PHÁO HOA CÙNG NHAU - Olew",
        duration: 279,
        url: "https://youtube.com/watch?v=ndLYTg_roj0",
        thumbnail: "https://i.ytimg.com/vi/ndLYTg_roj0/hq720.jpg",
        author: "Olew Thích Hát",
      },
      {
        video_id: "Q8e80Sd4jqc",
        title: "KARAOKE | Không Buông - Hngle x Ari | Chạy chữ dễ hát",
        duration: 175,
        url: "https://youtube.com/watch?v=Q8e80Sd4jqc",
        thumbnail: "https://i.ytimg.com/vi/Q8e80Sd4jqc/hq720.jpg",
        author: "Hát Cùng Huy",
      },
      {
        video_id: "VVm769D2bok",
        title: "Orange - 'CHÚNG TA CÒN Ở ĐÓ KHÔNG?' Karaoke - Tone Nữ",
        duration: 246,
        url: "https://youtube.com/watch?v=VVm769D2bok",
        thumbnail: "https://i.ytimg.com/vi/VVm769D2bok/hq720.jpg",
        author: "Orange Singer Official",
      },
      {
        video_id: "__FlQTTepx8",
        title: "[Karaoke] Phương Mỹ Chi x DTAP - Bóng Phù Hoa | Sing!Asia",
        duration: 289,
        url: "https://youtube.com/watch?v=__FlQTTepx8",
        thumbnail: "https://i.ytimg.com/vi/__FlQTTepx8/hqdefault.jpg",
        author: "Hyuchi ",
      },
      {
        video_id: "y6f3bIb35W0",
        title:
          "KARAOKE BEAT CHUẨN || KỆ NHẮM MẮT YÊU LUÔN || HANA CẨM TIÊN ft TUỆ NY || TONE NỮ",
        duration: 195,
        url: "https://youtube.com/watch?v=y6f3bIb35W0",
        thumbnail: "https://i.ytimg.com/vi/y6f3bIb35W0/hq720.jpg",
        author: "Hana Cẩm Tiên Official",
      },
      {
        video_id: "o85NASygdTs",
        title: "10 MẤT 1 CÒN KHÔNG (KARAOKE) - LÊ GIA BẢO | BEAT CHUẨN (CÓ BÈ)",
        duration: 286,
        url: "https://youtube.com/watch?v=o85NASygdTs",
        thumbnail: "https://i.ytimg.com/vi/o85NASygdTs/hq720.jpg",
        author: "Lê Gia Bảo",
      },
      {
        video_id: "7ROQwj0HbG4",
        title: "[KARAOKE] NGÀN NĂM ÁNH SÁNG - ĐẶNG VĨNH THỊNH (CÓ BÈ)",
        duration: 215,
        url: "https://youtube.com/watch?v=7ROQwj0HbG4",
        thumbnail: "https://i.ytimg.com/vi/7ROQwj0HbG4/hq720.jpg",
        author: "dawn it pink",
      },
      {
        video_id: "cqKgIzHtWMQ",
        title: "Karaoke | Đi Cùng Em - Hà Tròn ft Lemon Climb | Beat Chuẩn",
        duration: 270,
        url: "https://youtube.com/watch?v=cqKgIzHtWMQ",
        thumbnail: "https://i.ytimg.com/vi/cqKgIzHtWMQ/hq720.jpg",
        author: "ACV Karaoke",
      },
      {
        video_id: "-G0YclNougw",
        title: "Karaoke Cô Bé Mùa Đông Tone Nữ | Nhan KTV",
        duration: 262,
        url: "https://youtube.com/watch?v=-G0YclNougw",
        thumbnail: "https://i.ytimg.com/vi/-G0YclNougw/hq720.jpg",
        author: "Nhan KTV",
      },
      {
        video_id: "uMNOxpqQ_08",
        title: "KARAOKE | CÒN GÌ ĐẸP HƠN - Nguyễn Hùng",
        duration: 283,
        url: "https://youtube.com/watch?v=uMNOxpqQ_08",
        thumbnail: "https://i.ytimg.com/vi/uMNOxpqQ_08/hq720.jpg",
        author: "TDH",
      },
      {
        video_id: "Wl44p2P1q-c",
        title:
          "Karaoke Từng Ngày Yêu Em (Version Hành trình thanh âm ZLAB) / buitruonglinh (Prod. Đậu Tấn Đạt)",
        duration: 224,
        url: "https://youtube.com/watch?v=Wl44p2P1q-c",
        thumbnail: "https://i.ytimg.com/vi/Wl44p2P1q-c/hq720.jpg",
        author: "Phạm Lêp",
      },
      {
        video_id: "G5k_z1GQ-3Y",
        title:
          "Duongg - Nắng Ấm Trong Tim | Karaoke Beat Gốc Funny Network | Lạc vào khu rừng hoa...",
        duration: 260,
        url: "https://youtube.com/watch?v=G5k_z1GQ-3Y",
        thumbnail: "https://i.ytimg.com/vi/G5k_z1GQ-3Y/hq720.jpg",
        author: "Funny Network",
      },
      {
        video_id: "omVVmZ_yQJ0",
        title: "(Karaoke Beat Chuẩn) Low G | In Love (ft. JustaTee)",
        duration: 299,
        url: "https://youtube.com/watch?v=omVVmZ_yQJ0",
        thumbnail: "https://i.ytimg.com/vi/omVVmZ_yQJ0/hq720.jpg",
        author: "chó sủa meo meo?",
      },
      {
        video_id: "VSjW9maC8VA",
        title: "[KARAOKE] bình yên - Vũ. ft. Binz",
        duration: 202,
        url: "https://youtube.com/watch?v=VSjW9maC8VA",
        thumbnail: "https://i.ytimg.com/vi/VSjW9maC8VA/hq720.jpg",
        author: "Warner Music Vietnam",
      },
      {
        video_id: "dq2GqZgc38A",
        title: "(S)TRONG Trọng Hiếu - Kho Báu | Karaoke Beat Chuẩn",
        duration: 199,
        url: "https://youtube.com/watch?v=dq2GqZgc38A",
        thumbnail: "https://i.ytimg.com/vi/dq2GqZgc38A/hq720.jpg",
        author: "Trong Hieu Official",
      },
      {
        video_id: "-CrZ6RTZb0Y",
        title: "KARAOKE | Chuyện Đôi Ta (Freak D Lofi Ver.) - Emcee L ft Muộii",
        duration: 212,
        url: "https://youtube.com/watch?v=-CrZ6RTZb0Y",
        thumbnail: "https://i.ytimg.com/vi/-CrZ6RTZb0Y/hq720.jpg",
        author: "Hát Cùng Orinn",
      },
      {
        video_id: "2zr9lBgUEu4",
        title: "Bầu Trời Mới - Da LAB ft. Minh Tốc & Lam KARAOKE ( Có bè )",
        duration: 263,
        url: "https://youtube.com/watch?v=2zr9lBgUEu4",
        thumbnail: "https://i.ytimg.com/vi/2zr9lBgUEu4/hq720.jpg",
        author: "Ban.G Instrumental",
      },
      {
        video_id: "ovjxTqCtmPs",
        title:
          "KARAOKE | GIỮ ANH CHO NGÀY HÔM QUA - HOÀNG DŨNG feat. RHYMASTIC",
        duration: 290,
        url: "https://youtube.com/watch?v=ovjxTqCtmPs",
        thumbnail: "https://i.ytimg.com/vi/ovjxTqCtmPs/hq720.jpg",
        author: "TDH",
      },
      {
        video_id: "3mQuD8xcmUw",
        title: "[KARAOKE] MƠ - Vũ Cát Tường Tone nữ [Beat chuẩn giọng nữ]",
        duration: 263,
        url: "https://youtube.com/watch?v=3mQuD8xcmUw",
        thumbnail: "https://i.ytimg.com/vi/3mQuD8xcmUw/hq720.jpg",
        author: "Trung Nguyen",
      },
      {
        video_id: "0kOKtLUaYok",
        title: "[KARAOKE VERSION] Ngày Đẹp Trời Để Nói Chia Tay - Lou Hoàng",
        duration: 221,
        url: "https://youtube.com/watch?v=0kOKtLUaYok",
        thumbnail: "https://i.ytimg.com/vi/0kOKtLUaYok/hq720.jpg",
        author: "Warner Music Vietnam",
      },
      {
        video_id: "XTHHqQx5hHo",
        title: "🪽THIÊN MỆNH🪽| QUÂN A.P ft HẢI ĐĂNG DOO | KARAOKE",
        duration: 250,
        url: "https://youtube.com/watch?v=XTHHqQx5hHo",
        thumbnail: "https://i.ytimg.com/vi/XTHHqQx5hHo/hq720.jpg",
        author: "Quân A.P Official",
      },
      {
        video_id: "TpoxMQARjTU",
        title: "CHƯA PHẢI LÀ YÊU - HURRYKNG (feat. REX) | KARAOKE (có đệm)",
        duration: 193,
        url: "https://youtube.com/watch?v=TpoxMQARjTU",
        thumbnail: "https://i.ytimg.com/vi/TpoxMQARjTU/hq720.jpg",
        author: "Satoru",
      },
      {
        video_id: "Qb1KESTtueU",
        title: "Orange - ' Gặp Lại Năm ta 60 ' Karaoke Tone Nữ - Beat Gốc",
        duration: 329,
        url: "https://youtube.com/watch?v=Qb1KESTtueU",
        thumbnail: "https://i.ytimg.com/vi/Qb1KESTtueU/hq720.jpg",
        author: "Orange Singer Official",
      },
      {
        video_id: "dkiBtNpNW-8",
        title:
          "[ KARAOKE ]  GIÁ NHƯ - SOOBIN |  Anh Trai Vượt Ngàn Chông Gai 2024",
        duration: 164,
        url: "https://youtube.com/watch?v=dkiBtNpNW-8",
        thumbnail: "https://i.ytimg.com/vi/dkiBtNpNW-8/hq720.jpg",
        author: "YEAH1 MUSIC",
      },
      {
        video_id: "4a0cr8gx7so",
        title:
          "[KARAOKE] đưa em về nhàa - GREY D ft. Chillies | Instrumental/ Beat Gốc (Tone Nam)",
        duration: 240,
        url: "https://youtube.com/watch?v=4a0cr8gx7so",
        thumbnail: "https://i.ytimg.com/vi/4a0cr8gx7so/hq720.jpg",
        author: "GREY D",
      },
      {
        video_id: "l0LbcmE0H5I",
        title:
          "ERIK - 'Tha Thứ Cho Nhau Được Không?' (Karaoke) - OST MV from 'Chốt Đơn' movie",
        duration: 254,
        url: "https://youtube.com/watch?v=l0LbcmE0H5I",
        thumbnail: "https://i.ytimg.com/vi/l0LbcmE0H5I/hq720.jpg",
        author: "ERIK Official",
      },
      {
        video_id: "smV3FnOlBsc",
        title:
          "Mãi Chẳng Thuộc Về Nhau - Bozitt [ Beat Gốc / Karaoke] TONE NAM | 4B Studio",
        duration: 381,
        url: "https://youtube.com/watch?v=smV3FnOlBsc",
        thumbnail: "https://i.ytimg.com/vi/smV3FnOlBsc/hq720.jpg",
        author: "4B Studio",
      },
    ],
  },

  {
    id: CategoriesId.ANH_TRAI_SAY_HI,
    name: "Vũ Trụ Say Hi",
    image: categoryImages[CategoriesId.ANH_TRAI_SAY_HI],
    videos: [
      {
        video_id: "ey8sceAwpx0",
        title: '[KARAOKE] ĐỘC NHẤT VÔ NHỊ | Anh Trai "Say Hi" 2025',
        duration: 280,
        url: "https://youtube.com/watch?v=ey8sceAwpx0",
        thumbnail: "https://i.ytimg.com/vi/ey8sceAwpx0/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "gpE-YNXQtUo",
        title: "[KARAOKE] Make Up (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 257,
        url: "https://youtube.com/watch?v=gpE-YNXQtUo",
        thumbnail: "https://i.ytimg.com/vi/gpE-YNXQtUo/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "cEo_iv6vApw",
        title:
          '[KARAOKE] NGƯỜI NHƯ ANH XỨNG ĐÁNG CÔ ĐƠN | Anh Trai "Say Hi" 2025',
        duration: 337,
        url: "https://youtube.com/watch?v=cEo_iv6vApw",
        thumbnail: "https://i.ytimg.com/vi/cEo_iv6vApw/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "oWbPYvH8-SY",
        title: '[KARAOKE] HERMOSA | Anh Trai "Say Hi" 2025',
        duration: 265,
        url: "https://youtube.com/watch?v=oWbPYvH8-SY",
        thumbnail: "https://i.ytimg.com/vi/oWbPYvH8-SY/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "DkYWa3BUzVE",
        title: '[KARAOKE] ĐA NGHI | Anh Trai "Say Hi" 2025',
        duration: 278,
        url: "https://youtube.com/watch?v=DkYWa3BUzVE",
        thumbnail: "https://i.ytimg.com/vi/DkYWa3BUzVE/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "LxfmuDvZI_o",
        title: "[KARAOKE] CAN I GET YOUR LOVE (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 301,
        url: "https://youtube.com/watch?v=LxfmuDvZI_o",
        thumbnail: "https://i.ytimg.com/vi/LxfmuDvZI_o/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "-UrQItsPkMQ",
        title: '[KARAOKE] HƠN LÀ BẠN | Anh Trai "Say Hi" 2025',
        duration: 248,
        url: "https://youtube.com/watch?v=-UrQItsPkMQ",
        thumbnail: "https://i.ytimg.com/vi/-UrQItsPkMQ/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "UePPePMZBxw",
        title: '[KARAOKE] CHẠM | Anh Trai "Say Hi" 2025',
        duration: 265,
        url: "https://youtube.com/watch?v=UePPePMZBxw",
        thumbnail: "https://i.ytimg.com/vi/UePPePMZBxw/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "VepZGIE85lc",
        title: '[KARAOKE] SO GOOD | Anh Trai "Say Hi" 2025',
        duration: 261,
        url: "https://youtube.com/watch?v=VepZGIE85lc",
        thumbnail: "https://i.ytimg.com/vi/VepZGIE85lc/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "8A-U-2QqWN8",
        title: '[KARAOKE] ĐOẠN KỊCH CÂM | Anh Trai "Say Hi" 2025',
        duration: 259,
        url: "https://youtube.com/watch?v=8A-U-2QqWN8",
        thumbnail: "https://i.ytimg.com/vi/8A-U-2QqWN8/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "Aqhxecx7nxg",
        title: "[KARAOKE] Sớm Muộn Thì (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 336,
        url: "https://youtube.com/watch?v=Aqhxecx7nxg",
        thumbnail: "https://i.ytimg.com/vi/Aqhxecx7nxg/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "bK64n-D30ts",
        title: '[KARAOKE] ĐÃ TỪNG | Anh Trai "Say Hi" 2025',
        duration: 301,
        url: "https://youtube.com/watch?v=bK64n-D30ts",
        thumbnail: "https://i.ytimg.com/vi/bK64n-D30ts/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "kMHPR6QunK8",
        title:
          "[KARAOKE] Cũng May Là Ế (Beat Chuẩn) | Có Rap | Anh Trai Say Hi",
        duration: 226,
        url: "https://youtube.com/watch?v=kMHPR6QunK8",
        thumbnail: "https://i.ytimg.com/vi/kMHPR6QunK8/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "Ow5tyXewNJU",
        title: '[KARAOKE] ẢO ẢNH | Anh Trai "Say Hi" 2025',
        duration: 284,
        url: "https://youtube.com/watch?v=Ow5tyXewNJU",
        thumbnail: "https://i.ytimg.com/vi/Ow5tyXewNJU/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "MS-WmS3waZk",
        title: '[KARAOKE] CHILL GUYS NGON ZAI | Anh Trai "Say Hi" 2025',
        duration: 249,
        url: "https://youtube.com/watch?v=MS-WmS3waZk",
        thumbnail: "https://i.ytimg.com/vi/MS-WmS3waZk/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "PuARVXVQqz8",
        title: '[KARAOKE] THIÊU THÂN | Anh Trai "Say Hi" 2025',
        duration: 223,
        url: "https://youtube.com/watch?v=PuARVXVQqz8",
        thumbnail: "https://i.ytimg.com/vi/PuARVXVQqz8/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "bMn31HPdZ4U",
        title:
          "[Karaoke] NGƯỜI YÊU CHƯA SINH RA KARAOKE - OgeNus,BigDaddy,Robber,Phúc Du,ATSH |Anh Trai Say Hi 2025",
        duration: 232,
        url: "https://youtube.com/watch?v=bMn31HPdZ4U",
        thumbnail: "https://i.ytimg.com/vi/bMn31HPdZ4U/hq720.jpg",
        author: "Hoàng Bs KaRAP",
      },
      {
        video_id: "bDjzJuk5he8",
        title:
          "THOÁT RA KHỎI EM - RIO, Phúc Du, Thái Ngân, Jey B (Color Coded Lyrics) | Anh Trai Say Hi",
        duration: 542,
        url: "https://youtube.com/watch?v=bDjzJuk5he8",
        thumbnail: "https://i.ytimg.com/vi/bDjzJuk5he8/hq720.jpg",
        author: "VieShows and 2 more",
      },
      {
        video_id: "KyDwuXhioVo",
        title: "[KARAOKE] CRAZY (Beat Chuẩn) | Có Bè | Anh Trai Say Hi",
        duration: 213,
        url: "https://youtube.com/watch?v=KyDwuXhioVo",
        thumbnail: "https://i.ytimg.com/vi/KyDwuXhioVo/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "XOj1_J_3pjw",
        title:
          "[KARAOKE] Dẫu Có Đến Đâu – Lohan, Nhâm Phương Nam, Vương Bình, CONGB | Beat Có Bè | Anh Trai Say Hi",
        duration: 229,
        url: "https://youtube.com/watch?v=XOj1_J_3pjw",
        thumbnail: "https://i.ytimg.com/vi/XOj1_J_3pjw/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "v10nTunkUqU",
        title: '[KARAOKE] 3 CHÌM 7 NỔI | Anh Trai "Say Hi" 2025',
        duration: 263,
        url: "https://youtube.com/watch?v=v10nTunkUqU",
        thumbnail: "https://i.ytimg.com/vi/v10nTunkUqU/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "YNsMXSPd4kM",
        title:
          "【LYRICS】 3 CHÌM 7 NỔI - Anh Trai Say Hi 2025 (Color Coded Lyrics)",
        duration: 247,
        url: "https://youtube.com/watch?v=YNsMXSPd4kM",
        thumbnail: "https://i.ytimg.com/vi/YNsMXSPd4kM/hqdefault.jpg",
        author: "Quang Say2",
      },
      {
        video_id: "izcXKZPLCFU",
        title: "[KARAOKE] TO YOUR EX (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 268,
        url: "https://youtube.com/watch?v=izcXKZPLCFU",
        thumbnail: "https://i.ytimg.com/vi/izcXKZPLCFU/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "v56DUdv8RNQ",
        title: "[KARAOKE] Em Đã Chờ Anh Bao Lâu (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 323,
        url: "https://youtube.com/watch?v=v56DUdv8RNQ",
        thumbnail: "https://i.ytimg.com/vi/v56DUdv8RNQ/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "pTovcq9j8dU",
        title:
          "[KARAOKE] Ở Đây Ai Cũng Thương Con (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 280,
        url: "https://youtube.com/watch?v=pTovcq9j8dU",
        thumbnail: "https://i.ytimg.com/vi/pTovcq9j8dU/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "H1ZgpQfcySQ",
        title: "[KARAOKE] Thức (Tone Nữ) | Có Bè | Anh Trai Say Hi",
        duration: 327,
        url: "https://youtube.com/watch?v=H1ZgpQfcySQ",
        thumbnail: "https://i.ytimg.com/vi/H1ZgpQfcySQ/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "FUvfA6CK3iI",
        title: "[KARAOKE] Vô Số Lần Tình Cờ (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 237,
        url: "https://youtube.com/watch?v=FUvfA6CK3iI",
        thumbnail: "https://i.ytimg.com/vi/FUvfA6CK3iI/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "RH3Sal9ZbIQ",
        title: "[KARAOKE] Kẻ Hai Lời (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 258,
        url: "https://youtube.com/watch?v=RH3Sal9ZbIQ",
        thumbnail: "https://i.ytimg.com/vi/RH3Sal9ZbIQ/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "l1AC0uaZXuc",
        title: "[KARAOKE] Đêm Giáng Sinh Mùa Hạ (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 334,
        url: "https://youtube.com/watch?v=l1AC0uaZXuc",
        thumbnail: "https://i.ytimg.com/vi/l1AC0uaZXuc/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "UU0X4OITljI",
        title: "[KARAOKE] Nỡ Lòng Đồng Ý (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 297,
        url: "https://youtube.com/watch?v=UU0X4OITljI",
        thumbnail: "https://i.ytimg.com/vi/UU0X4OITljI/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "ORiWvpGZG90",
        title: "[KARAOKE] Trực Giác (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 318,
        url: "https://youtube.com/watch?v=ORiWvpGZG90",
        thumbnail: "https://i.ytimg.com/vi/ORiWvpGZG90/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "ge9ELv8Fi3E",
        title: "[KARAOKE] BOUNCE (Beat Chuẩn) | Anh Trai Say Hi",
        duration: 240,
        url: "https://youtube.com/watch?v=ge9ELv8Fi3E",
        thumbnail: "https://i.ytimg.com/vi/ge9ELv8Fi3E/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "GeT1EGP-oRs",
        title:
          "[KARAOKE] Trở Thành Người Em Muốn (Beat Chuẩn) - Jey B | Anh Trai Say Hi",
        duration: 255,
        url: "https://youtube.com/watch?v=GeT1EGP-oRs",
        thumbnail: "https://i.ytimg.com/vi/GeT1EGP-oRs/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "0kc7M2Heal4",
        title:
          "[KARAOKE] Đừng Biến Mất Hôm Nay (Beat Chuẩn) - Phạm Đình Thái Ngân |   Anh Trai Say Hi",
        duration: 246,
        url: "https://youtube.com/watch?v=0kc7M2Heal4",
        thumbnail: "https://i.ytimg.com/vi/0kc7M2Heal4/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "8b99rI7Wmdw",
        title:
          "[KARAOKE] Bí Mật Nhỏ (Beat Chuẩn) - Mason Nguyễn | Anh Trai Say Hi",
        duration: 215,
        url: "https://youtube.com/watch?v=8b99rI7Wmdw",
        thumbnail: "https://i.ytimg.com/vi/8b99rI7Wmdw/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "du9NtTrAj2A",
        title:
          "[KARAOKE] Anh Không Đến Để Rời Đi (Beat Chuẩn) - OgeNus | Anh Trai Say Hi",
        duration: 238,
        url: "https://youtube.com/watch?v=du9NtTrAj2A",
        thumbnail: "https://i.ytimg.com/vi/du9NtTrAj2A/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "vPSEL2eKE7Q",
        title:
          "[KARAOKE] Vạn Lý Độc Hành (Beat Chuẩn) - Karik | Anh Trai Say Hi",
        duration: 243,
        url: "https://youtube.com/watch?v=vPSEL2eKE7Q",
        thumbnail: "https://i.ytimg.com/vi/vPSEL2eKE7Q/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "fWkMHP39V0I",
        title:
          "[KARAOKE] Đường Chân Trời (Beat Chuẩn) - Bùi Trường Linh | Anh Trai Say Hi",
        duration: 296,
        url: "https://youtube.com/watch?v=fWkMHP39V0I",
        thumbnail: "https://i.ytimg.com/vi/fWkMHP39V0I/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "DXH1s0cnOCs",
        title:
          "[KARAOKE] Một Tâm Hồn Bình Thản (Beat Chuẩn) - HUSTLANG Robber | Anh Trai Say Hi",
        duration: 263,
        url: "https://youtube.com/watch?v=DXH1s0cnOCs",
        thumbnail: "https://i.ytimg.com/vi/DXH1s0cnOCs/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "yXfZCQXwKCI",
        title:
          "[KARAOKE] IT'S GON' BE ALRIGHT (Beat Chuẩn) - Negav | Anh Trai Say Hi",
        duration: 242,
        url: "https://youtube.com/watch?v=yXfZCQXwKCI",
        thumbnail: "https://i.ytimg.com/vi/yXfZCQXwKCI/hq720.jpg",
        author: "TY & KARAOKE",
      },
      {
        video_id: "5zMhhfGfWfY",
        title:
          "[Karaoke Beat] AAA - Liên Quân 2 | Em Xinh Say Hi (Beat Chuẩn Có Bè)",
        duration: 237,
        url: "https://youtube.com/watch?v=5zMhhfGfWfY",
        thumbnail: "https://i.ytimg.com/vi/5zMhhfGfWfY/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "dE8sWAGmtbM",
        title:
          "[Karaoke Beat] ĐÃ XINH LẠI CÒN THÔNG MINH - Liên Quân 1 | Em Xinh Say Hi (Beat Chuẩn Có Bè)",
        duration: 237,
        url: "https://youtube.com/watch?v=dE8sWAGmtbM",
        thumbnail: "https://i.ytimg.com/vi/dE8sWAGmtbM/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "MHGiBATIxyM",
        title:
          "[Karaoke Beat] EASIER - MAIQUINN, Ngô Lan Hương, Muộii, Đào Tử A1J, Saabirose (Beat Có Bè)",
        duration: 199,
        url: "https://youtube.com/watch?v=MHGiBATIxyM",
        thumbnail: "https://i.ytimg.com/vi/MHGiBATIxyM/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "Cbtc2hPqdfQ",
        title:
          "[KARAOKE] ĐỒNG DAO XINH GÁI - Miu Lê, Quỳnh Anh Shyn, Vũ Thảo My, Orange, Mỹ Mỹ | Em Xinh Say Hi",
        duration: 242,
        url: "https://youtube.com/watch?v=Cbtc2hPqdfQ",
        thumbnail: "https://i.ytimg.com/vi/Cbtc2hPqdfQ/hqdefault.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "_6__EHyWHX4",
        title:
          "[Karaoke Beat] RUN - Châu Bùi, Ánh Sáng AZA, 52Hz, Yeolan, LyHan (Beat Chuẩn Có Bè)",
        duration: 248,
        url: "https://youtube.com/watch?v=_6__EHyWHX4",
        thumbnail: "https://i.ytimg.com/vi/_6__EHyWHX4/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "JchPP2NyBxk",
        title:
          "[KARAOKE] TỪNG - LyLy, Danmy, Han Sara, Lâm Bảo Ngọc, Liu Grace | Em Xinh Say Hi",
        duration: 283,
        url: "https://youtube.com/watch?v=JchPP2NyBxk",
        thumbnail: "https://i.ytimg.com/vi/JchPP2NyBxk/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "PI3QvOg5Gog",
        title:
          "[Karaoke Beat] Em Xinh Em Bling - Pháo, Phương Ly, Juky San, Chi Xê, Hoàng Duyên (Beat Có Bè)",
        duration: 203,
        url: "https://youtube.com/watch?v=PI3QvOg5Gog",
        thumbnail: "https://i.ytimg.com/vi/PI3QvOg5Gog/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "akKq-2kpGQY",
        title:
          "[KARAOKE] CẦM KỲ THI HOẠ - Bích Phương, Tiên Tiên, Lamoon, Phương Mỹ Chi, Bảo Anh | Em Xinh Say Hi",
        duration: 247,
        url: "https://youtube.com/watch?v=akKq-2kpGQY",
        thumbnail: "https://i.ytimg.com/vi/akKq-2kpGQY/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "LH2ydAQirWw",
        title: "The Real Aura KARAOKE - Em Xinh Say Hi Theme Song (beat gốc)",
        duration: 297,
        url: "https://youtube.com/watch?v=LH2ydAQirWw",
        thumbnail: "https://i.ytimg.com/vi/LH2ydAQirWw/hq720.jpg",
        author: "Penny Ziippy",
      },
      {
        video_id: "LWyX238zuTw",
        title:
          "[KARAOKE] HỀ - Phương Mỹ Chi, Phương Ly, Pháo, Chi Xê, WEAN | Em Xinh Say Hi",
        duration: 285,
        url: "https://youtube.com/watch?v=LWyX238zuTw",
        thumbnail: "https://i.ytimg.com/vi/LWyX238zuTw/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "Bfjbi62auSE",
        title:
          "[Karaoke Beat] RED FLAG - Yeolan, Ngô Lan Hương, Han Sara, Lamoon, Jsol (Beat Chuẩn Có Bè)",
        duration: 235,
        url: "https://youtube.com/watch?v=Bfjbi62auSE",
        thumbnail: "https://i.ytimg.com/vi/Bfjbi62auSE/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "CKfR7ZrA9qM",
        title:
          "[KARAOKE] WE BELONG TOGETHER - Miu Lê, Juky San, Lyly, Danmy, Dương Domic | Em Xinh Say Hi",
        duration: 308,
        url: "https://youtube.com/watch?v=CKfR7ZrA9qM",
        thumbnail: "https://i.ytimg.com/vi/CKfR7ZrA9qM/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "K4zfGa0xSyE",
        title:
          "[KARAOKE] KHÔNG ĐAU NỮA RỒI - 52Hz, Orange, Mỹ Mỹ, Châu Bùi, Pháp Kiều | Em Xinh Say Hi",
        duration: 311,
        url: "https://youtube.com/watch?v=K4zfGa0xSyE",
        thumbnail: "https://i.ytimg.com/vi/K4zfGa0xSyE/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "-KnFLfPSrTw",
        title:
          "[KARAOKE] GÃ SĂN CÁ - Quang Hùng MasterD, Saabirose, Lâm Bảo Ngọc, MAIQUINN, Quỳnh Anh Shyn | EXSH",
        duration: 248,
        url: "https://youtube.com/watch?v=-KnFLfPSrTw",
        thumbnail: "https://i.ytimg.com/vi/-KnFLfPSrTw/hqdefault.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "SLsxoLoer6U",
        title:
          "[KARAOKE] EM CHỈ LÀ - Bích Phương, Tăng Duy Tân, LyHan, Muộii, Hoàng Duyên | Em Xinh Say Hi",
        duration: 322,
        url: "https://youtube.com/watch?v=SLsxoLoer6U",
        thumbnail: "https://i.ytimg.com/vi/SLsxoLoer6U/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "TENDSFkMv2E",
        title: 'Karaoke không bè rap - PERFECT | Em Xinh "Say Hi"',
        duration: 250,
        url: "https://youtube.com/watch?v=TENDSFkMv2E",
        thumbnail: "https://i.ytimg.com/vi/TENDSFkMv2E/hq720.jpg",
        author: "Họa Mi",
      },
      {
        video_id: "lLmr0Ao6_KE",
        title:
          "[KARAOKE]ĐIỀU EM LUÔN MONG MUỐN - Đào Tử A1J,Vũ Thảo My,Tiên Tiên,Hùng Huỳnh|PonxVie|Bản quyền€VieON",
        duration: 197,
        url: "https://youtube.com/watch?v=lLmr0Ao6_KE",
        thumbnail: "https://i.ytimg.com/vi/lLmr0Ao6_KE/hq720.jpg",
        author: "PonPTGamer",
      },
      {
        video_id: "w3lW9hHvl2k",
        title:
          "[KARAOKE] I'LL BE THERE - Lamoon, Phương Mỹ Chi, Orange, Han Sara | Em Xinh Say Hi",
        duration: 256,
        url: "https://youtube.com/watch?v=w3lW9hHvl2k",
        thumbnail: "https://i.ytimg.com/vi/w3lW9hHvl2k/hq720.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "2XHcd7TTOos",
        title:
          "[KARAOKE] NOT MY FAULT - Mỹ Mỹ, LyHan, MaiQuinn, Liu Grace l EXSH ( BEAT CHUẨN )",
        duration: 255,
        url: "https://youtube.com/watch?v=2XHcd7TTOos",
        thumbnail: "https://i.ytimg.com/vi/2XHcd7TTOos/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "R_sRKgQZNPo",
        title:
          "[KARAOKE] SO ĐẬM - Phương Ly, Vũ Thảo My, Muộii, Châu Bùi | EXSH",
        duration: 168,
        url: "https://youtube.com/watch?v=R_sRKgQZNPo",
        thumbnail: "https://i.ytimg.com/vi/R_sRKgQZNPo/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "ZpCBN6CUpgo",
        title:
          "[KARAOKE] EM KHÔNG CÓ ƯA - Tiên Tiên, Bảo Anh, Saabirose, Ánh Sáng AZA | EXSH",
        duration: 181,
        url: "https://youtube.com/watch?v=ZpCBN6CUpgo",
        thumbnail: "https://i.ytimg.com/vi/ZpCBN6CUpgo/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "HHtm4Kb3u0U",
        title:
          "[KARAOKE] LỜI THẬT LÒNG KHI SAY - Miu Lê, Bích Phương, Juky San, Quỳnh Anh Shyn | EXSH",
        duration: 177,
        url: "https://youtube.com/watch?v=HHtm4Kb3u0U",
        thumbnail: "https://i.ytimg.com/vi/HHtm4Kb3u0U/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "qldyjtqrdb8",
        title:
          "[KARAOKE] CỨ ĐỔ TẠI CƠN MƯA - Phương Ly, Châu Bùi, Vũ Thảo My, Orange, 52Hz | Em Xinh Say Hi",
        duration: 271,
        url: "https://youtube.com/watch?v=qldyjtqrdb8",
        thumbnail: "https://i.ytimg.com/vi/qldyjtqrdb8/hqdefault.jpg",
        author: "Vie Channel - MUSIC",
      },
      {
        video_id: "NSudBFtFX_s",
        title:
          "[KARAOKE] CHẲNG PHẢI ANH ĐÂU - Phương Ly, Orange, Châu Bùi, 52Hz, Vũ Thảo My | EXSH ( BEAT CHUẨN )",
        duration: 215,
        url: "https://youtube.com/watch?v=NSudBFtFX_s",
        thumbnail: "https://i.ytimg.com/vi/NSudBFtFX_s/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "9NEFezfKvVA",
        title:
          "[KARAOKE] CÁCH (YÊU ĐÚNG) ĐIỆU - Bích Phương, Juky San, Quỳnh Anh Shyn, Mỹ Mỹ, Lamoon ( BEAT CHUẨN )",
        duration: 270,
        url: "https://youtube.com/watch?v=9NEFezfKvVA",
        thumbnail: "https://i.ytimg.com/vi/9NEFezfKvVA/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "NClCvZCd8Uk",
        title:
          "[KARAOKE] BAD LIAR - Lâm Bảo Ngọc, Pháo, Phương Mỹ Chi, Saabirose, Liu Grace | EXSH ( BEAT CHUẨN )",
        duration: 260,
        url: "https://youtube.com/watch?v=NClCvZCd8Uk",
        thumbnail: "https://i.ytimg.com/vi/NClCvZCd8Uk/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "DVhuuJ8JBDs",
        title:
          "[KARAOKE] BẮC THANG LÊN HỎI ÔNG TRỜI - Bích Phương, Lamoon, Juky San, Quỳnh Anh Shyn, Mỹ Mỹ | EXSH",
        duration: 227,
        url: "https://youtube.com/watch?v=DVhuuJ8JBDs",
        thumbnail: "https://i.ytimg.com/vi/DVhuuJ8JBDs/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "eVgQ_iaUvWU",
        title:
          "[KARAOKE] LẮM LÚC - LyHan x Miu Lê x Tiên Tiên x MAIQUINN x Bảo Anh | Em Xinh Say Hi ( BEAT CÓ BÈ )",
        duration: 265,
        url: "https://youtube.com/watch?v=eVgQ_iaUvWU",
        thumbnail: "https://i.ytimg.com/vi/eVgQ_iaUvWU/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "lVn6DfOqEPo",
        title:
          "[KARAOKE] DUYÊN - Lâm Bảo Ngọc, Phương Mỹ Chi, Pháo, Saabirose, Liu Grace | EXSH ( BEAT CÓ BÈ )",
        duration: 258,
        url: "https://youtube.com/watch?v=lVn6DfOqEPo",
        thumbnail: "https://i.ytimg.com/vi/lVn6DfOqEPo/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "ivVNyn2Mr0M",
        title:
          "[KARAOKE] TÍN HIỆU YÊU - LyHan, Miu Lê, Tiên Tiên, MAIQUINN, Bảo Anh | EXSH ( BEAT CHUẨN )",
        duration: 197,
        url: "https://youtube.com/watch?v=ivVNyn2Mr0M",
        thumbnail: "https://i.ytimg.com/vi/ivVNyn2Mr0M/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "IPnxs7TKvLo",
        title: "[KARAOKE] ẾCH NGOÀI ĐÁY GIẾNG - Phương Mỹ Chi l ( BEAT CHUẨN )",
        duration: 243,
        url: "https://youtube.com/watch?v=IPnxs7TKvLo",
        thumbnail: "https://i.ytimg.com/vi/IPnxs7TKvLo/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "WCw2u6SY4pM",
        title:
          "[ KARAOKE BEAT GỐC ] ÁI KỶ - LÂM BẢO NGỌC | EM XINH SAY HI MÙA 1 TẬP 12 | CÓ BACKING VOCAL",
        duration: 246,
        url: "https://youtube.com/watch?v=WCw2u6SY4pM",
        thumbnail: "https://i.ytimg.com/vi/WCw2u6SY4pM/hq720.jpg",
        author: "Hoàng 03K  🎵🎬",
      },
      {
        video_id: "XeE-6mQ1GJU",
        title: "Cô ấy không yêu anh Karaoke(Beat gốc)_Bảo Anh Phúc Du",
        duration: 242,
        url: "https://youtube.com/watch?v=XeE-6mQ1GJU",
        thumbnail: "https://i.ytimg.com/vi/XeE-6mQ1GJU/hq720.jpg",
        author: "Kafka",
      },
      {
        video_id: "V5h2dhbCPxQ",
        title: "[KARAOKE] DƯƠNG GIAN - Lamoon l ( BEAT CHUẨN )",
        duration: 240,
        url: "https://youtube.com/watch?v=V5h2dhbCPxQ",
        thumbnail: "https://i.ytimg.com/vi/V5h2dhbCPxQ/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "OVkomNKuJA0",
        title:
          "[ KARAOKE BEAT GỐC ] TRỜI SAO - 52Hz | EM XINH SAY HI MÙA 1 TẬP 12",
        duration: 325,
        url: "https://youtube.com/watch?v=OVkomNKuJA0",
        thumbnail: "https://i.ytimg.com/vi/OVkomNKuJA0/hq720.jpg",
        author: "Hoàng 03K  🎵🎬",
      },
      {
        video_id: "6oKzMRGXKVk",
        title:
          "THAO TÚNG TÂM LÝ - MAIQUINN (Color Coded Lyrics) | EM XINH SAY HI",
        duration: 488,
        url: "https://youtube.com/watch?v=6oKzMRGXKVk",
        thumbnail: "https://i.ytimg.com/vi/6oKzMRGXKVk/hq720.jpg",
        author: "VieShows",
      },
      {
        video_id: "9nuHYqhQeOk",
        title: "LỜI THÚ TỘI KARAOKE | SAABIROSE EM XINH SAY HI",
        duration: 255,
        url: "https://youtube.com/watch?v=9nuHYqhQeOk",
        thumbnail: "https://i.ytimg.com/vi/9nuHYqhQeOk/hq720.jpg",
        author: "PY Music",
      },
      {
        video_id: "kVEmjC_vYug",
        title: "[KARAOKE] NGƯỜI ĐẦU TIÊN - Juky San l ( BEAT CHUẨN )",
        duration: 243,
        url: "https://youtube.com/watch?v=kVEmjC_vYug",
        thumbnail: "https://i.ytimg.com/vi/kVEmjC_vYug/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "3Ug0w06Zm1w",
        title: "[KARAOKE] RƠI TỰ DO - LyHan l ( BEAT CHUẨN )",
        duration: 212,
        url: "https://youtube.com/watch?v=3Ug0w06Zm1w",
        thumbnail: "https://i.ytimg.com/vi/3Ug0w06Zm1w/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "_kEAGY_GY9Q",
        title: "[KARAOKE] CHU KỲ MỚI - Bích Phương l ( BEAT CHUẨN )",
        duration: 311,
        url: "https://youtube.com/watch?v=_kEAGY_GY9Q",
        thumbnail: "https://i.ytimg.com/vi/_kEAGY_GY9Q/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "raOzT0AoAvg",
        title: "[KARAOKE] ĐI VỀ - PHÁO NORTHSIDE l ( BEAT CHUẨN )",
        duration: 216,
        url: "https://youtube.com/watch?v=raOzT0AoAvg",
        thumbnail: "https://i.ytimg.com/vi/raOzT0AoAvg/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "ae_3pu1GVbc",
        title: "Em Thích Là Được - Miu Lê Bản Karaoke",
        duration: 194,
        url: "https://youtube.com/watch?v=ae_3pu1GVbc",
        thumbnail: "https://i.ytimg.com/vi/ae_3pu1GVbc/hq720.jpg",
        author: "Mĩ Ân",
      },
      {
        video_id: "XKIji-7RgtM",
        title: "[KARAOKE] VỖ TAY - Phương Ly l ( BEAT CHUẨN )",
        duration: 252,
        url: "https://youtube.com/watch?v=XKIji-7RgtM",
        thumbnail: "https://i.ytimg.com/vi/XKIji-7RgtM/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "G8fj0kaa3DA",
        title: "LIVE MY WAY - Tiên Tiên (Color Coded Lyrics) | EM XINH SAY HI",
        duration: 581,
        url: "https://youtube.com/watch?v=G8fj0kaa3DA",
        thumbnail: "https://i.ytimg.com/vi/G8fj0kaa3DA/hq720.jpg",
        author: "VieShows",
      },
      {
        video_id: "YMPUpswIeIM",
        title: "[KARAOKE] LỘI NGƯỢC DÒNG - ORANGE l ( BEAT CHUẨN )",
        duration: 203,
        url: "https://youtube.com/watch?v=YMPUpswIeIM",
        thumbnail: "https://i.ytimg.com/vi/YMPUpswIeIM/hq720.jpg",
        author: "NHL Entertainment",
      },
      {
        video_id: "RjfKevZToSo",
        title: "ĐAN BÀN TAY - Châu Bùi (Color Coded Lyrics) | EM XINH SAY HI",
        duration: 571,
        url: "https://youtube.com/watch?v=RjfKevZToSo",
        thumbnail: "https://i.ytimg.com/vi/RjfKevZToSo/hq720.jpg",
        author: "VieShows",
      },
      {
        video_id: "XPBFoHE0U3o",
        title:
          "Karaoke - 'Tình Đầu Quá Chén' - Quang Hùng MasterD (ft. Negav, Erik, Pháp Kiều)",
        duration: 292,
        url: "https://youtube.com/watch?v=XPBFoHE0U3o",
        thumbnail: "https://i.ytimg.com/vi/XPBFoHE0U3o/hq720.jpg",
        author: "Quang Hùng MasterD",
      },
      {
        video_id: "GGto2sCQE9Q",
        title:
          "[Karaoke] Kim Phút Kim Giờ - ATSH (HIEUTHUHAI, Pháp Kiều, Negav, HURRYKNG, Isaac) | Vie Offical",
        duration: 293,
        url: "https://youtube.com/watch?v=GGto2sCQE9Q",
        thumbnail: "https://i.ytimg.com/vi/GGto2sCQE9Q/hq720.jpg",
        author: "Vie Official",
      },
      {
        video_id: "a6wg-XhA4fk",
        title:
          "(KARAOKE) HÀO QUANG - Rhyder, Dương Domic, Pháp Kiều | Anh Trai Say Hi ( BEAT CHUẨN )",
        duration: 243,
        url: "https://youtube.com/watch?v=a6wg-XhA4fk",
        thumbnail: "https://i.ytimg.com/vi/a6wg-XhA4fk/hq720.jpg",
        author: "Sunemee Karaoke",
      },
      {
        video_id: "NQeBDu_W8Yw",
        title:
          "KARAOKE Chân Thành  Rhyder, Ali Hoàng Dương, Quang Hùng, Wean Lê, Captain",
        duration: 253,
        url: "https://youtube.com/watch?v=NQeBDu_W8Yw",
        thumbnail: "https://i.ytimg.com/vi/NQeBDu_W8Yw/hq720.jpg",
        author: "Hihi",
      },
      {
        video_id: "0nAcgYCM-8I",
        title: "Karaoke - 'Trói Em Lại' - Quang Hùng MasterD",
        duration: 267,
        url: "https://youtube.com/watch?v=0nAcgYCM-8I",
        thumbnail: "https://i.ytimg.com/vi/0nAcgYCM-8I/hq720.jpg",
        author: "Quang Hùng MasterD",
      },
      {
        video_id: "MCqsm3a69bE",
        title:
          "[KARAOKE - Beat Chuẩn] Sao Hạng A - HIEUTHUHAI, Jsol, Song Luân, Dương Domic | Anh Trai Say Hi",
        duration: 252,
        url: "https://youtube.com/watch?v=MCqsm3a69bE",
        thumbnail: "https://i.ytimg.com/vi/MCqsm3a69bE/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "iy8YBm0LBuY",
        title:
          "KARAOKE CATCH ME IF YOU CAN - Negav, Quang Hùng MasterD, Nicky, Công Dương",
        duration: 257,
        url: "https://youtube.com/watch?v=iy8YBm0LBuY",
        thumbnail: "https://i.ytimg.com/vi/iy8YBm0LBuY/hq720.jpg",
        author: "LK Music",
      },
      {
        video_id: "u1h5l3LkryY",
        title:
          "[KARAOKE] I'M THINKING ABOUT YOU (Beat Chuẩn) - Rhyder, Wean, Đức Phúc, Hùng Huỳnh ft. Tlinh",
        duration: 196,
        url: "https://youtube.com/watch?v=u1h5l3LkryY",
        thumbnail: "https://i.ytimg.com/vi/u1h5l3LkryY/hq720.jpg",
        author: "LK Music",
      },
      {
        video_id: "6uuN1eG72E8",
        title:
          "[Karaoke Beat] REGRET - LÂM BẢO NGỌC, QUÂN A.P, QUANG TRUNG, ALI HOÀNG DƯƠNG, PHÁP KIỀU (Beat Chuẩn)",
        duration: 253,
        url: "https://youtube.com/watch?v=6uuN1eG72E8",
        thumbnail: "https://i.ytimg.com/vi/6uuN1eG72E8/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "pS8QPIiFTFs",
        title:
          "[KARAOKE] BAO LỜI CON CHƯA NÓI (Beat chuẩn, bè)- Atus, Quang Trung, Anh Tú, Dương Domic, Song Luân",
        duration: 298,
        url: "https://youtube.com/watch?v=pS8QPIiFTFs",
        thumbnail: "https://i.ytimg.com/vi/pS8QPIiFTFs/hq720.jpg",
        author: "LK Music",
      },
      {
        video_id: "5udDeOooLM4",
        title:
          "[KARAOKE - Bè Rap] Cứ Để Anh Ta Rời Đi - Song Luân, Bảo Anh, Dương Domic, Quang Hùng, Lou Hoàng",
        duration: 274,
        url: "https://youtube.com/watch?v=5udDeOooLM4",
        thumbnail: "https://i.ytimg.com/vi/5udDeOooLM4/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "0qTp5VlLCZw",
        title:
          "[Karaoke Beat] ĐỀU LÀ CỦA EM - ANH TÚ, ATUS, SONG LUÂN, DƯƠNG DOMIC, QUANG TRUNG (Beat Chuẩn Có Bè)",
        duration: 239,
        url: "https://youtube.com/watch?v=0qTp5VlLCZw",
        thumbnail: "https://i.ytimg.com/vi/0qTp5VlLCZw/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "bxCxQBae-k8",
        title: "Karaoke Don't Care - Anh Trai Say 2 | Beat Chuẩn 2035",
        duration: 260,
        url: "https://youtube.com/watch?v=bxCxQBae-k8",
        thumbnail: "https://i.ytimg.com/vi/bxCxQBae-k8/hq720.jpg",
        author: "SFC V-pop",
      },
      {
        video_id: "VcYBtUIvRec",
        title:
          "(KARAOKE) ĐẦU ĐỘI SỪNG - HURRYKNG x Quân AP x Gemini Hùng Huỳnh | ANH TRAI SAY HI (BEAT CHUẨN)",
        duration: 215,
        url: "https://youtube.com/watch?v=VcYBtUIvRec",
        thumbnail: "https://i.ytimg.com/vi/VcYBtUIvRec/hq720.jpg",
        author: "Sunemee Karaoke",
      },
      {
        video_id: "CFm_nCPUgec",
        title: "[Karaoke Beat Chuẩn] QUAY ĐI QUAY LẠI - Hieuthuhai",
        duration: 210,
        url: "https://youtube.com/watch?v=CFm_nCPUgec",
        thumbnail: "https://i.ytimg.com/vi/CFm_nCPUgec/hq720.jpg",
        author: "Vkaraoke",
      },
      {
        video_id: "N0SSCuPFK_Q",
        title:
          "[KARAOKE - Bè Rap] WALK - HIEUTHUHAI, Hurrykng, Negav, Isaac, Pháp Kiều | Anh Trai Say Hi - VieOn",
        duration: 230,
        url: "https://youtube.com/watch?v=N0SSCuPFK_Q",
        thumbnail: "https://i.ytimg.com/vi/N0SSCuPFK_Q/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "0qTp5VlLCZw",
        title:
          "[Karaoke Beat] ĐỀU LÀ CỦA EM - ANH TÚ, ATUS, SONG LUÂN, DƯƠNG DOMIC, QUANG TRUNG (Beat Chuẩn Có Bè)",
        duration: 239,
        url: "https://youtube.com/watch?v=0qTp5VlLCZw",
        thumbnail: "https://i.ytimg.com/vi/0qTp5VlLCZw/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "9vbdBhlfvD8",
        title:
          "KARAOKE LOVE SAND   HIEUTHUHAI, Jsol, Ali Hoàng Dương, Vũ Thịnh so hot   Anh Trai Say Hi",
        duration: 236,
        url: "https://youtube.com/watch?v=9vbdBhlfvD8",
        thumbnail: "https://i.ytimg.com/vi/9vbdBhlfvD8/hqdefault.jpg",
        author: "Hihi",
      },
      {
        video_id: "1orzFFpbQx0",
        title:
          "[Karaoke Beat] THI SĨ - ERIK, ĐỨC PHÚC, PHẠM ANH DUY, TAGE (Beat Chuẩn Có Bè)",
        duration: 289,
        url: "https://youtube.com/watch?v=1orzFFpbQx0",
        thumbnail: "https://i.ytimg.com/vi/1orzFFpbQx0/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "xqXeRi5tAJI",
        title: "NGÁO NGƠ KARAOKE ( CÓ BÈ ) HIEUTHUHAI X JSOL X ERIK X ANH TÚ",
        duration: 253,
        url: "https://youtube.com/watch?v=xqXeRi5tAJI",
        thumbnail: "https://i.ytimg.com/vi/xqXeRi5tAJI/hq720.jpg",
        author: "Huy Cùi Music",
      },
      {
        video_id: "q52wqJ8rEds",
        title: '[KARAOKE] TRÀN BỘ NHỚ - DƯƠNG DOMIC | EP "DỮ LIỆU QUÝ"',
        duration: 191,
        url: "https://youtube.com/watch?v=q52wqJ8rEds",
        thumbnail: "https://i.ytimg.com/vi/q52wqJ8rEds/hq720.jpg",
        author: "Internity",
      },
      {
        video_id: "40_mQYQpIts",
        title: "[KARAOKE] Anh Biết Rồi - RHYDER | Anh Trai Say Hi - VieOn",
        duration: 260,
        url: "https://youtube.com/watch?v=40_mQYQpIts",
        thumbnail: "https://i.ytimg.com/vi/40_mQYQpIts/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "B3vI4AVk3eg",
        title:
          "[KARAOKE - Bè Rap] S.O.S - Rhyder, WEAN, Quang Hùng MasterD, Ali Hoàng  Dương, Captain | ATSH",
        duration: 267,
        url: "https://youtube.com/watch?v=B3vI4AVk3eg",
        thumbnail: "https://i.ytimg.com/vi/B3vI4AVk3eg/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "vq0-ln9Ixj4",
        title:
          "[KARAOKE] SAU ĐÊM NAY (Beat chuẩn) - Erik, Quân A.P, Jsol, Đức Phúc, Hùng Huỳnh | Anh Trai Say Hi",
        duration: 290,
        url: "https://youtube.com/watch?v=vq0-ln9Ixj4",
        thumbnail: "https://i.ytimg.com/vi/vq0-ln9Ixj4/hq720.jpg",
        author: "LK Music",
      },
      {
        video_id: "_p5oXFD_ceU",
        title:
          "[KARAOKE - Bè Rap] Anh Trai Nước Việt - Erik, Quân AP, Jsol, Đức Phúc, Hùng Huỳnh Gemini | ATSH",
        duration: 273,
        url: "https://youtube.com/watch?v=_p5oXFD_ceU",
        thumbnail: "https://i.ytimg.com/vi/_p5oXFD_ceU/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "Y1xqah8JKtU",
        title:
          "KARAOKE NGÂN NGA   Vũ Thảo My, Isaac, Negav, HURRYKNG, Gin Tuấn Kiệt   Anh Trai Say Hi",
        duration: 279,
        url: "https://youtube.com/watch?v=Y1xqah8JKtU",
        thumbnail: "https://i.ytimg.com/vi/Y1xqah8JKtU/hqdefault.jpg",
        author: "Hihi",
      },
      {
        video_id: "iN1yPLPJohY",
        title:
          "[Karaoke Beat] SÓNG VỖ VỠ BỜ - ANH TÚ, ERIK, ANH DUY, JSOL, DƯƠNG DOMIC (Beat Chuẩn Có Bè)",
        duration: 324,
        url: "https://youtube.com/watch?v=iN1yPLPJohY",
        thumbnail: "https://i.ytimg.com/vi/iN1yPLPJohY/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "OVkZDNH0CXw",
        title:
          "[Karaoke Beat] NGƯỜI TÌNH CỦA NẮNG - ANH TÚ, CAPTAIN, VŨ THỊNH, HẢI ĐĂNG DOO, LYLY (Beat Chuẩn)",
        duration: 241,
        url: "https://youtube.com/watch?v=OVkZDNH0CXw",
        thumbnail: "https://i.ytimg.com/vi/OVkZDNH0CXw/hq720.jpg",
        author: "Hoàng Anh Potatoes",
      },
      {
        video_id: "2Nii_byePuA",
        title:
          "KARAOKE HÍT  DRAMA    Isaac, Anh Tú, WEAN, Đỗ Phú Quí   Anh Trai Say Hi",
        duration: 294,
        url: "https://youtube.com/watch?v=2Nii_byePuA",
        thumbnail: "https://i.ytimg.com/vi/2Nii_byePuA/hq720.jpg",
        author: "Hihi",
      },
      {
        video_id: "Ni7gmi6rEBk",
        title: "Karaoke 10/10 - Anh Trai Say 2 | Beat Siu Chuẩn",
        duration: 217,
        url: "https://youtube.com/watch?v=Ni7gmi6rEBk",
        thumbnail: "https://i.ytimg.com/vi/Ni7gmi6rEBk/hq720.jpg",
        author: "SFC V-pop",
      },
      {
        video_id: "Zu5ftKf1B-o",
        title: "Karaoke HÚT - Anh Trai Say 2 | Beat Chuẩn 2036",
        duration: 206,
        url: "https://youtube.com/watch?v=Zu5ftKf1B-o",
        thumbnail: "https://i.ytimg.com/vi/Zu5ftKf1B-o/hq720.jpg",
        author: "SFC V-pop",
      },
      {
        video_id: "f_-PouKaJ1U",
        title:
          "Nỗi Đau Ngây Dại Karaoke ( Beat Chuẩn ) Đức Phúc - HIEUTHUHAI - Công Dương",
        duration: 259,
        url: "https://youtube.com/watch?v=f_-PouKaJ1U",
        thumbnail: "https://i.ytimg.com/vi/f_-PouKaJ1U/hq720.jpg",
        author: "Huy Cùi Music",
      },
      {
        video_id: "GV7kowYXC8s",
        title: "Karaoke BẢNH - Anh Trai Say 2 | Beat Chuẩn 2025",
        duration: 232,
        url: "https://youtube.com/watch?v=GV7kowYXC8s",
        thumbnail: "https://i.ytimg.com/vi/GV7kowYXC8s/hqdefault.jpg",
        author: "SFC V-pop",
      },
      {
        video_id: "_1tnihIaX80",
        title: "Karaoke I.C.O.N - Anh Trai Say 2 | Beat Chuan 2024",
        duration: 214,
        url: "https://youtube.com/watch?v=_1tnihIaX80",
        thumbnail: "https://i.ytimg.com/vi/_1tnihIaX80/hq720.jpg",
        author: "SFC V-pop",
      },
      {
        video_id: "r-7OxdD_16w",
        title: "Karaoke NGẠO NGHỄ   Anh Trai Say 2    Chuẩn 2024",
        duration: 201,
        url: "https://youtube.com/watch?v=r-7OxdD_16w",
        thumbnail: "https://i.ytimg.com/vi/r-7OxdD_16w/hq720.jpg",
        author: "TH STUDIO PRO",
      },
      {
        video_id: "0I-JdbDf8lc",
        title:
          "[KARAOKE] ĐÓA HỒNG CHƠI VƠI - Anh Tú | Cứ ngỡ bông hoa xinh tươi chẳng cô đơn... | ANH TRAI SAY HI",
        duration: 315,
        url: "https://youtube.com/watch?v=0I-JdbDf8lc",
        thumbnail: "https://i.ytimg.com/vi/0I-JdbDf8lc/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "R37Kx8XmyXs",
        title:
          "ĐOÁ PHÙ DUNG CUỐI CÙNG (Karaoke) - ĐỨC PHÚC | OFFICIAL KARAOKE |  INSTRUMENTAL",
        duration: 325,
        url: "https://youtube.com/watch?v=R37Kx8XmyXs",
        thumbnail: "https://i.ytimg.com/vi/R37Kx8XmyXs/hq720.jpg",
        author: "ĐỨC PHÚC OFFICIAL",
      },
      {
        video_id: "wk0nPyAbYyM",
        title:
          "[KARAOKE - Bè Rap] Chàng Khờ Thủy Cung - Negav, Grey D | Anh Trai Say Hi - VieOn",
        duration: 307,
        url: "https://youtube.com/watch?v=wk0nPyAbYyM",
        thumbnail: "https://i.ytimg.com/vi/wk0nPyAbYyM/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "kyagrgGZy9U",
        title: "[KARAOKE] Tình Cuối Cùng - JSOL | Anh Trai Say Hi - VieOn",
        duration: 231,
        url: "https://youtube.com/watch?v=kyagrgGZy9U",
        thumbnail: "https://i.ytimg.com/vi/kyagrgGZy9U/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "cNS9wp-mXxc",
        title:
          "[KARAOKE - Bè Rap] Em Không Muốn Một Mình - Anh Tú Atus | Anh Trai Say Hi - VieOn",
        duration: 190,
        url: "https://youtube.com/watch?v=cNS9wp-mXxc",
        thumbnail: "https://i.ytimg.com/vi/cNS9wp-mXxc/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "sz-EsVDLFBc",
        title: "[KARAOKE] Khiêu Vũ Dưới Trăng - Erik | Anh Trai Say Hi - VieOn",
        duration: 264,
        url: "https://youtube.com/watch?v=sz-EsVDLFBc",
        thumbnail: "https://i.ytimg.com/vi/sz-EsVDLFBc/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "10EMalRcchQ",
        title: "GỌI CHO ANH - ISAAC (KARAOKE)",
        duration: 175,
        url: "https://youtube.com/watch?v=10EMalRcchQ",
        thumbnail: "https://i.ytimg.com/vi/10EMalRcchQ/hqdefault.jpg",
        author: "Levi",
      },
      {
        video_id: "dAy3D2CkkAQ",
        title: "[KARAOKE BEAT CHUẨN] KIM TỰ THÁP - CAPTAIN BOY",
        duration: 271,
        url: "https://youtube.com/watch?v=dAy3D2CkkAQ",
        thumbnail: "https://i.ytimg.com/vi/dAy3D2CkkAQ/hq720.jpg",
        author: "Tủ đồ của Đức Duy",
      },
      {
        video_id: "zc4wkjyYuek",
        title:
          "[KARAOKE - Bè Rap] COLORS - Pháp Kiều | Anh Trai Say Hi - VieOn",
        duration: 228,
        url: "https://youtube.com/watch?v=zc4wkjyYuek",
        thumbnail: "https://i.ytimg.com/vi/zc4wkjyYuek/hq720.jpg",
        author: "Moonlight 2",
      },
      {
        video_id: "o7tumI1A2cc",
        title:
          "[KARAOKE] AIRPLANE MODE - HURRYKNG cùng WEAN quẩy nhiệt cùng dàn anh | Anh Trai Say Hi",
        duration: 204,
        url: "https://youtube.com/watch?v=o7tumI1A2cc",
        thumbnail: "https://i.ytimg.com/vi/o7tumI1A2cc/hq720.jpg",
        author: "Channel_12.6.9",
      },
      {
        video_id: "C2hgqyetXH8",
        title:
          "[ KARAOKE CÓ BÈ ] Say Hi Never Say Goodbye - 30 Anh Trai | Anh Trai Say Hi",
        duration: 295,
        url: "https://youtube.com/watch?v=C2hgqyetXH8",
        thumbnail: "https://i.ytimg.com/vi/C2hgqyetXH8/hq720.jpg",
        author: "MEOW MUSIC",
      },
    ],
  },
  {
    id: CategoriesId.RAP_VIET,
    name: "Rap Việt",
    image: categoryImages[CategoriesId.RAP_VIET],
    videos: [
      {
        video_id: "ed3Z2x5qyYM",
        title:
          "[Karaoke] Khu tao sống - Wowy ft. Karik (Beat Phối chuẩn) - Http://newtitanvn.com",
        duration: 245,
        url: "https://youtube.com/watch?v=ed3Z2x5qyYM",
        thumbnail: "https://i.ytimg.com/vi/ed3Z2x5qyYM/hq720.jpg",
        author: "Hồng Nguyễn",
      },
      {
        video_id: "gWsRNHprJFI",
        title: "[ KARAOKE ] HAI THẾ GIỚI - WOWY x KARIK | VN KARA",
        duration: 279,
        url: "https://youtube.com/watch?v=gWsRNHprJFI",
        thumbnail: "https://i.ytimg.com/vi/gWsRNHprJFI/hq720.jpg",
        author: "VN KARAOKE ",
      },
      {
        video_id: "-sBLkqkDeKI",
        title:
          "Karaoke Nàng - OgeNus - Team BigDaddy | Rap Việt 2023 | ZKN Music",
        duration: 199,
        url: "https://youtube.com/watch?v=-sBLkqkDeKI",
        thumbnail: "https://i.ytimg.com/vi/-sBLkqkDeKI/hq720.jpg",
        author: "ZKN Music",
      },
      {
        video_id: "iOxvOlCyaVM",
        title: "Ghé Qua - Dick x PC x Tofu | Karaoke.",
        duration: 235,
        url: "https://youtube.com/watch?v=iOxvOlCyaVM",
        thumbnail: "https://i.ytimg.com/vi/iOxvOlCyaVM/hq720.jpg",
        author: "Đức Studio",
      },
      {
        video_id: "t0fPV7RUWvo",
        title:
          "Karaoke QUA TỪNG KHUNG HÌNH (Có Bè) - NGẮN và Robber | Beat Chuẩn | ZKN Music",
        duration: 241,
        url: "https://youtube.com/watch?v=t0fPV7RUWvo",
        thumbnail: "https://i.ytimg.com/vi/t0fPV7RUWvo/hq720.jpg",
        author: "ZKN Music",
      },
      {
        video_id: "maMcxtZvOj8",
        title:
          "Karaoke Cao Ốc 20 (Có Hook) | B RAY x DatG (ft MASEW x K-ICM) | ZKN Music",
        duration: 255,
        url: "https://youtube.com/watch?v=maMcxtZvOj8",
        thumbnail: "https://i.ytimg.com/vi/maMcxtZvOj8/hq720.jpg",
        author: "ZKN Music 2",
      },
      {
        video_id: "woBak43AtJk",
        title:
          "Karaoke Westside Squad (Beat Gốc) tụi mày chỉ biết hút không chịu đi khám phá",
        duration: 181,
        url: "https://youtube.com/watch?v=woBak43AtJk",
        thumbnail: "https://i.ytimg.com/vi/woBak43AtJk/hq720.jpg",
        author: "G5R Karaoke",
      },
      {
        video_id: "TWKuHcEwIfE",
        title:
          "Hẹn Gặp Em Dưới Ánh Trăng - Karaoke (Vocal 30%) KEN 20250108001",
        duration: 222,
        url: "https://youtube.com/watch?v=TWKuHcEwIfE",
        thumbnail: "https://i.ytimg.com/vi/TWKuHcEwIfE/hqdefault.jpg",
        author: "Anh thợ văn phòng dzui zẻ",
      },
      {
        video_id: "PhVO-g7i4OM",
        title: "KARAOKE RAP ĐÔI MẮT | GDUCKY ft ANH TÚ",
        duration: 151,
        url: "https://youtube.com/watch?v=PhVO-g7i4OM",
        thumbnail: "https://i.ytimg.com/vi/PhVO-g7i4OM/hq720.jpg",
        author: "Cảnh Mai Đức",
      },
      {
        video_id: "cgRpJ1ZJGtU",
        title:
          "Karaoke WRONG TIMES - PUPPY & DANGRANGTO | Beat Chuẩn | ZKN Music",
        duration: 217,
        url: "https://youtube.com/watch?v=cgRpJ1ZJGtU",
        thumbnail: "https://i.ytimg.com/vi/cgRpJ1ZJGtU/hq720.jpg",
        author: "ZKN Music",
      },
      {
        video_id: "2XyvUlEUU_s",
        title: "Karaoke TUYẾT TRÊN PHỐ - GILL | Karaoke Beat Chuẩn | ZKN Music",
        duration: 223,
        url: "https://youtube.com/watch?v=2XyvUlEUU_s",
        thumbnail: "https://i.ytimg.com/vi/2XyvUlEUU_s/hq720.jpg",
        author: "ZKN Music",
      },
      {
        video_id: "CiBcniXakOE",
        title:
          "Karaoke Tuyết Yêu Thương Remix - Giang Jolee | Từng Bông Tuyết Trắng Rơi Bên Thềm Remix TikTok",
        duration: 213,
        url: "https://youtube.com/watch?v=CiBcniXakOE",
        thumbnail: "https://i.ytimg.com/vi/CiBcniXakOE/hq720.jpg",
        author: "H2O Karaoke",
      },
      {
        video_id: "bzJc8mq9ZiM",
        title: "Karaoke Khi Cơn Mơ Dần Phai   Tez, Myra Trần",
        duration: 189,
        url: "https://youtube.com/watch?v=bzJc8mq9ZiM",
        thumbnail: "https://i.ytimg.com/vi/bzJc8mq9ZiM/hq720.jpg",
        author: "Dong Tam",
      },
      {
        video_id: "jfar0_FTtt8",
        title: "Mamma Mia (Karaoke) - Gerdnang",
        duration: 224,
        url: "https://youtube.com/watch?v=jfar0_FTtt8",
        thumbnail: "https://i.ytimg.com/vi/jfar0_FTtt8/hqdefault.jpg",
        author: "Đổi tên để dễ hát Karaoke",
      },
      {
        video_id: "cigkq3A5mbU",
        title:
          "KARAOKE | ĐỔI TƯ THẾ - BÌNH GOLD x ANDREE RIGHT HAND | ORIGINAL INSTRUMENTAL",
        duration: 246,
        url: "https://youtube.com/watch?v=cigkq3A5mbU",
        thumbnail: "https://i.ytimg.com/vi/cigkq3A5mbU/hq720.jpg",
        author: "Bâus & Cánh Gà",
      },
      {
        video_id: "feJR9mAm0z8",
        title:
          "Ổ QUỶ - DMT, Nguyễn Băng Qua, Trần Lả Lướt, Rocky CDE - Official MV",
        duration: 248,
        url: "https://youtube.com/watch?v=feJR9mAm0z8",
        thumbnail: "https://i.ytimg.com/vi/feJR9mAm0z8/hq720.jpg",
        author: "Ruv",
      },
      {
        video_id: "GyPk5Ygn2IU",
        title: "TETVOVEN (KARAOKE)- Wxrdie ft Andree Right Hand & Machiot",
        duration: 221,
        url: "https://youtube.com/watch?v=GyPk5Ygn2IU",
        thumbnail: "https://i.ytimg.com/vi/GyPk5Ygn2IU/hqdefault.jpg",
        author: "Đức Thịnh",
      },
      {
        video_id: "0FFXAKMRyjg",
        title: "tlinh - nếu lúc đó | karaoke",
        duration: 264,
        url: "https://youtube.com/watch?v=0FFXAKMRyjg",
        thumbnail: "https://i.ytimg.com/vi/0FFXAKMRyjg/hq720.jpg",
        author: "tlinh",
      },
      {
        video_id: "iXKw9cFV2ts",
        title: "Pháo | SỰ NGHIỆP CHƯỚNG - KARAOKE",
        duration: 201,
        url: "https://youtube.com/watch?v=iXKw9cFV2ts",
        thumbnail: "https://i.ytimg.com/vi/iXKw9cFV2ts/hq720.jpg",
        author: "Một bài Dizz",
      },
      {
        video_id: "4n33PVZ3OQ0",
        title: "Karaoke Chạy - GDucky, Tez | Rap Việt Mùa 1 | ZKN Music",
        duration: 223,
        url: "https://youtube.com/watch?v=4n33PVZ3OQ0",
        thumbnail: "https://i.ytimg.com/vi/4n33PVZ3OQ0/hq720.jpg",
        author: "ZKN Music",
      },
      {
        video_id: "fqJ99WLuBWE",
        title: "[karaoke] Thương- karik ft Uyên pim",
        duration: 176,
        url: "https://youtube.com/watch?v=fqJ99WLuBWE",
        thumbnail: "https://i.ytimg.com/vi/fqJ99WLuBWE/hqdefault.jpg",
        author: "Bay Boy Love",
      },
    ],
  },

  {
    id: CategoriesId.SONG_CA,
    name: "Song Ca",
    image: categoryImages[CategoriesId.SONG_CA],
    videos: [
      {
        video_id: "IpSeS7bdOa4",
        title:
          "[KARAOKE SONG CA] - NƠI TÌNH YÊU BẮT ĐẦU - Bằng Kiều ft Lam Anh",
        duration: 282,
        url: "https://youtube.com/watch?v=IpSeS7bdOa4",
        thumbnail: "https://i.ytimg.com/vi/IpSeS7bdOa4/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "MJVfZACz68A",
        title:
          "KARAOKE | Ngày Ta Có Nhau - LyLy x Anh Tú | Khắc Hưng | PNJ | Y T KALAKOLE",
        duration: 391,
        url: "https://youtube.com/watch?v=MJVfZACz68A",
        thumbnail: "https://i.ytimg.com/vi/MJVfZACz68A/hq720.jpg",
        author: "Y T KALAKOLE",
      },
      {
        video_id: "VrWFRJcIi1I",
        title: "Đừng Xin Lỗi Nữa Karaoke   Min/Erik  Beat Gốc",
        duration: 230,
        url: "https://youtube.com/watch?v=VrWFRJcIi1I",
        thumbnail: "https://i.ytimg.com/vi/VrWFRJcIi1I/hq720.jpg",
        author: "Ngô Tuệ",
      },
      {
        video_id: "deB8vpbmf5M",
        title:
          "Say Yes - OgeNus và PiaLinh | Chọn Gì? Chọn ĐI! | OFFICIAL KARAOKE",
        duration: 222,
        url: "https://youtube.com/watch?v=deB8vpbmf5M",
        thumbnail: "https://i.ytimg.com/vi/deB8vpbmf5M/hq720.jpg",
        author: "Chọn Gì? Chọn ĐI!",
      },
      {
        video_id: "RrfVTPWBBDs",
        title: "Vì Mẹ Anh Bắt Chia Tay - Karaoke Nguyên Bản | MGR",
        duration: 265,
        url: "https://youtube.com/watch?v=RrfVTPWBBDs",
        thumbnail: "https://i.ytimg.com/vi/RrfVTPWBBDs/hq720.jpg",
        author: "MGR KARAOKE",
      },
      {
        video_id: "g5swLzGGjEs",
        title:
          "Gặp Nhưng Không Ở Lại - Karaoke Tone Nữ Chuẩn | Hiền Hồ Ft. Vương Anh Tú",
        duration: 282,
        url: "https://youtube.com/watch?v=g5swLzGGjEs",
        thumbnail: "https://i.ytimg.com/vi/g5swLzGGjEs/hq720.jpg",
        author: "Hiền Hồ Official",
      },
      {
        video_id: "p5R7jTdCCVY",
        title:
          "[Karaoke] Tình Yêu Màu Nắng  Bigdaddy ft Đoàn Thúy Trang Full (BEAT CHUẨN)",
        duration: 304,
        url: "https://youtube.com/watch?v=p5R7jTdCCVY",
        thumbnail: "https://i.ytimg.com/vi/p5R7jTdCCVY/hq720.jpg",
        author: "Trịnh Đức Anh",
      },
      {
        video_id: "KuG7JC449AE",
        title:
          "Karaoke | Đếm Ngày Xa Em - Only C ft. Lou Hoàng (BEAT HẠ 1.5 TONE)",
        duration: 256,
        url: "https://youtube.com/watch?v=KuG7JC449AE",
        thumbnail: "https://i.ytimg.com/vi/KuG7JC449AE/hq720.jpg",
        author: "NMT",
      },
      {
        video_id: "GAc_G1tonwg",
        title:
          "[ KARAOKE BEAT CHUẨN ] BẮC BLING ( BẮC NINH ) - HOÀ MINZY FT NS XUÂN HINH x MASEW x TUẤN CRY",
        duration: 259,
        url: "https://youtube.com/watch?v=GAc_G1tonwg",
        thumbnail: "https://i.ytimg.com/vi/GAc_G1tonwg/hq720.jpg",
        author: "Hòa Minzy",
      },
      {
        video_id: "_O_m_kkHLj8",
        title: "Xin Anh Đừng - Emily ft. Lil' Knight.JustaTee ( karaoke )",
        duration: 207,
        url: "https://youtube.com/watch?v=_O_m_kkHLj8",
        thumbnail: "https://i.ytimg.com/vi/_O_m_kkHLj8/hq720.jpg",
        author: "Hà Bùi Thị",
      },
      {
        video_id: "q8mFT5qTegg",
        title:
          "Beat Chuẩn - BẠN ĐỜI - KARIK - (FT. GDUCKY) - KARAOKE CHUẨN DỄ HÁT",
        duration: 273,
        url: "https://youtube.com/watch?v=q8mFT5qTegg",
        thumbnail: "https://i.ytimg.com/vi/q8mFT5qTegg/hq720.jpg",
        author: "Karaoke Beat Gốc",
      },
      {
        video_id: "qNbXYIVhqoo",
        title: "[KARAOKE] KHI EM LỚN _Orange x Hoàng Dũng - Beat chuẩn (maN)",
        duration: 228,
        url: "https://youtube.com/watch?v=qNbXYIVhqoo",
        thumbnail: "https://i.ytimg.com/vi/qNbXYIVhqoo/hq720.jpg",
        author: "Nguyễn Hà Nam",
      },
      {
        video_id: "4dfGHeoMvqs",
        title:
          "[KARAOKE BEAT GỐC] MƯA THÁNG SÁU - VĂN MAI HƯƠNG ft. GREY D, TRUNG QUÂN (Prod. by HỨA KIM TUYỀN)",
        duration: 258,
        url: "https://youtube.com/watch?v=4dfGHeoMvqs",
        thumbnail: "https://i.ytimg.com/vi/4dfGHeoMvqs/hq720.jpg",
        author: "VĂN MAI HƯƠNG OFFICIAL",
      },
      {
        video_id: "15swO2LRcG4",
        title:
          "[KARAOKE] để tôi ôm em bằng giai điệu này - KAI ĐINH x MIN x GREY D | Instrumental/ Lofi Beat",
        duration: 265,
        url: "https://youtube.com/watch?v=15swO2LRcG4",
        thumbnail: "https://i.ytimg.com/vi/15swO2LRcG4/hq720.jpg",
        author: "Kai Dinh Official",
      },
      {
        video_id: "FDdqvu0dpH8",
        title:
          "Cơn Mưa Tình Yêu - Karaoke - Song Ca - Hà Anh Tuấn ft Phương Linh",
        duration: 292,
        url: "https://youtube.com/watch?v=FDdqvu0dpH8",
        thumbnail: "https://i.ytimg.com/vi/FDdqvu0dpH8/hq720.jpg",
        author: "Yeah ! Smile",
      },
      {
        video_id: "iUvEFK5W-JA",
        title: "[Karaoke] Thiên Đường Gọi Tên beat Hà An Huy và Phương Linh",
        duration: 250,
        url: "https://youtube.com/watch?v=iUvEFK5W-JA",
        thumbnail: "https://i.ytimg.com/vi/iUvEFK5W-JA/hq720.jpg",
        author: "Mê Hát",
      },
      {
        video_id: "sYzdTm2cxOE",
        title:
          "Anh Đánh Rơi Người Yêu Này - Andiez ft. AMEE | Karaoke Beat Chuẩn",
        duration: 208,
        url: "https://youtube.com/watch?v=sYzdTm2cxOE",
        thumbnail: "https://i.ytimg.com/vi/sYzdTm2cxOE/hq720.jpg",
        author: "Minh Hiếu Official",
      },
      {
        video_id: "q0ALJx-XM5M",
        title: "Karaoke Ngày Hạnh Phúc Hồ Ngọc Hà ft nhóm VMusic",
        duration: 311,
        url: "https://youtube.com/watch?v=q0ALJx-XM5M",
        thumbnail: "https://i.ytimg.com/vi/q0ALJx-XM5M/hq720.jpg",
        author: "Chin Anh",
      },
      {
        video_id: "z8dFh7vJoPY",
        title: "KARAOKE _ QUA ĐÊM NAY _ Phương Linh và Hà Anh Tuấn beat chuẩn",
        duration: 295,
        url: "https://youtube.com/watch?v=z8dFh7vJoPY",
        thumbnail: "https://i.ytimg.com/vi/z8dFh7vJoPY/hq720.jpg",
        author: "I'm Trinh",
      },
      {
        video_id: "q_1Vckcsz70",
        title:
          "Karaoke | Thời Thanh Xuân Sẽ Qua - Orange ft. Phạm Hồng Phước (XHTĐRLX) Beat Tách  ✅",
        duration: 257,
        url: "https://youtube.com/watch?v=q_1Vckcsz70",
        thumbnail: "https://i.ytimg.com/vi/q_1Vckcsz70/hq720.jpg",
        author: "Dương Trung KTV",
      },
      {
        video_id: "l5rtRuxUJ7o",
        title:
          "Mượn Rượu Tỏ Tình Beat Chuẩn   Karaoke Beat Chuẩn   BigDaddy Ft Emily",
        duration: 226,
        url: "https://youtube.com/watch?v=l5rtRuxUJ7o",
        thumbnail: "https://i.ytimg.com/vi/l5rtRuxUJ7o/hq720.jpg",
        author: "Music Karaoke (Melody)",
      },
      {
        video_id: "SsLiKrTTcwo",
        title: "Karaoke Yêu Một Người Có Lẽ   Miu Lê ft  Lou Hoàng Beat",
        duration: 251,
        url: "https://youtube.com/watch?v=SsLiKrTTcwo",
        thumbnail: "https://i.ytimg.com/vi/SsLiKrTTcwo/hq720.jpg",
        author: "thuong hieu vuive channel",
      },
      {
        video_id: "eFnvhFpM2pA",
        title: "TA LÀ CỦA NHAU KARAOKE ( BEAT CHUẨN )",
        duration: 179,
        url: "https://youtube.com/watch?v=eFnvhFpM2pA",
        thumbnail: "https://i.ytimg.com/vi/eFnvhFpM2pA/hq720.jpg",
        author: "NEIL HÀ OFFICIAL",
      },
      {
        video_id: "iFW_nq78INI",
        title: "AMEE x B RAY - Anh Nhà Ở Đâu Thế  Karaoke [Beat Chuẩn]",
        duration: 219,
        url: "https://youtube.com/watch?v=iFW_nq78INI",
        thumbnail: "https://i.ytimg.com/vi/iFW_nq78INI/hq720.jpg",
        author: "Best MusicMix",
      },
      {
        video_id: "Qu9cT38Cjds",
        title:
          "KARAOKE Cưới Nhau Đi (Beat Chuẩn không bè)  Yes I Do - Bùi Anh Tuấn if Hiền Hồ",
        duration: 263,
        url: "https://youtube.com/watch?v=Qu9cT38Cjds",
        thumbnail: "https://i.ytimg.com/vi/Qu9cT38Cjds/hq720.jpg",
        author: "Hoàng Nhật",
      },
      {
        video_id: "5nwYi1mxNVI",
        title:
          "KARAOKE| CHỈ LÀ KHÔNG CÙNG NHAU (Nhạc Hoa Lời Việt) | TĂNG PHÚC ft TRƯƠNG THẢO NHI | BEAT CHUẨN",
        duration: 235,
        url: "https://youtube.com/watch?v=5nwYi1mxNVI",
        thumbnail: "https://i.ytimg.com/vi/5nwYi1mxNVI/hq720.jpg",
        author: "TĂNG PHÚC OFFICIAL",
      },
      {
        video_id: "NVV2ysFeaPo",
        title:
          "[Karaoke] Bốn Chữ Lắm - Trúc Nhân ft. Trương Thảo Nhi [Song Ca]",
        duration: 260,
        url: "https://youtube.com/watch?v=NVV2ysFeaPo",
        thumbnail: "https://i.ytimg.com/vi/NVV2ysFeaPo/hq720.jpg",
        author: "Tài Nguyễn",
      },
      {
        video_id: "Wr9Xh3pzmUI",
        title: "[Karaoke] Tình về nơi đâu Full_Ken.Wasabi",
        duration: 250,
        url: "https://youtube.com/watch?v=Wr9Xh3pzmUI",
        thumbnail: "https://i.ytimg.com/vi/Wr9Xh3pzmUI/hqdefault.jpg",
        author: "kenny hpu",
      },
      {
        video_id: "qCjkN9iXBcc",
        title: "KARAOKE BEAT NGÀY MAI EM ĐI 2017   LÊ HIẾU ft SOOBIN HOÀNG SƠN",
        duration: 219,
        url: "https://youtube.com/watch?v=qCjkN9iXBcc",
        thumbnail: "https://i.ytimg.com/vi/qCjkN9iXBcc/hq720.jpg",
        author: "PDL Event",
      },
      {
        video_id: "LlkX6gcZy6A",
        title: "[Karaoke] Tình Yêu Ngủ Quên - Hoàng Tôn ft LyHan",
        duration: 188,
        url: "https://youtube.com/watch?v=LlkX6gcZy6A",
        thumbnail: "https://i.ytimg.com/vi/LlkX6gcZy6A/hqdefault.jpg",
        author: "QuyenAnh HD Official",
      },
      {
        video_id: "WpuLgWJcqrs",
        title:
          "Karaoke Nỗi Nhớ Đầy Vơi (Beat Gốc Bè) - Noo Phước Thịnh ft Hồ Ngọc Hà",
        duration: 306,
        url: "https://youtube.com/watch?v=WpuLgWJcqrs",
        thumbnail: "https://i.ytimg.com/vi/WpuLgWJcqrs/hq720.jpg",
        author: "N KTV",
      },
      {
        video_id: "CMVu3j5GznE",
        title: "[Karaoke] Mùa ta đã yêu-Hồng Phước Idol,Hương Giang Idol",
        duration: 229,
        url: "https://youtube.com/watch?v=CMVu3j5GznE",
        thumbnail: "https://i.ytimg.com/vi/CMVu3j5GznE/hqdefault.jpg",
        author: "kiên lê",
      },
      {
        video_id: "8vD-4doSzDs",
        title:
          "[KARAOKE] EX'S HATE ME (PART 2) - AMEE x B RAY | Instrumental/Beat Gốc (Tone Nữ)",
        duration: 217,
        url: "https://youtube.com/watch?v=8vD-4doSzDs",
        thumbnail: "https://i.ytimg.com/vi/8vD-4doSzDs/hq720.jpg",
        author: "AMEE",
      },
      {
        video_id: "Kgn2AErRfZQ",
        title: "Gác lại âu lo - Da LAB ft. Miu Lê (Official Karaoke Video)",
        duration: 307,
        url: "https://youtube.com/watch?v=Kgn2AErRfZQ",
        thumbnail: "https://i.ytimg.com/vi/Kgn2AErRfZQ/hq720.jpg",
        author: "Da LAB Official",
      },
      {
        video_id: "u62xH5MlRX8",
        title: "[Karaoke] Người Lạ Ơi",
        duration: 218,
        url: "https://youtube.com/watch?v=u62xH5MlRX8",
        thumbnail: "https://i.ytimg.com/vi/u62xH5MlRX8/hq720.jpg",
        author: "Thing",
      },
      {
        video_id: "76YTAIkq3NU",
        title:
          "KARAOKE | Ngôi Nhà Hoa Hồng - Quang Vinh x Bảo Thy | Beat phối mới chuẩn TONE GỐC ( Tone G - B )",
        duration: 340,
        url: "https://youtube.com/watch?v=76YTAIkq3NU",
        thumbnail: "https://i.ytimg.com/vi/76YTAIkq3NU/hq720.jpg",
        author: "Sang Bùi Studio OFFICIAL",
      },
      {
        video_id: "kAIuVahi9wU",
        title: "Karaoke Một Vòng Trái Đất ( Song Ca )",
        duration: 262,
        url: "https://youtube.com/watch?v=kAIuVahi9wU",
        thumbnail: "https://i.ytimg.com/vi/kAIuVahi9wU/hq720.jpg",
        author: "Tiên Over",
      },
      {
        video_id: "QRwlhPUcc50",
        title: "Karaoke Thu Cuối - Yanbi ft Mr T, Hằng Bing Boong full beat",
        duration: 287,
        url: "https://youtube.com/watch?v=QRwlhPUcc50",
        thumbnail: "https://i.ytimg.com/vi/QRwlhPUcc50/hq720.jpg",
        author: "Anh Nguyễn Đình",
      },
      {
        video_id: "DcETDzRvPmg",
        title: "KARAOKE Xe đạp - Thùy Chi M4U",
        duration: 286,
        url: "https://youtube.com/watch?v=DcETDzRvPmg",
        thumbnail: "https://i.ytimg.com/vi/DcETDzRvPmg/hq720.jpg",
        author: "Karaoke Việt HD",
      },
      {
        video_id: "fBrJ_x9CznU",
        title: "[Karaoke-TDP] Từng ngày anh mơ về em",
        duration: 207,
        url: "https://youtube.com/watch?v=fBrJ_x9CznU",
        thumbnail: "https://i.ytimg.com/vi/fBrJ_x9CznU/hqdefault.jpg",
        author: "TDP Dipain",
      },
      {
        video_id: "w7EGe320XU8",
        title:
          "[ Karaoke Song Ca ] Tận Cùng Nỗi Nhớ - Will ft Hansara (Beat chuẩn)",
        duration: 287,
        url: "https://youtube.com/watch?v=w7EGe320XU8",
        thumbnail: "https://i.ytimg.com/vi/w7EGe320XU8/hq720.jpg",
        author: "Hồng Ân Karaoke",
      },
      {
        video_id: "-CvSREY1I10",
        title: "Chưa Bao giờ Mẹ Kể full beat karaoke Min; Erik",
        duration: 259,
        url: "https://youtube.com/watch?v=-CvSREY1I10",
        thumbnail: "https://i.ytimg.com/vi/-CvSREY1I10/hq720.jpg",
        author: "Hàng Nhật Bãi VLOG",
      },
      {
        video_id: "Jox18WfgTV8",
        title: "Karaoke Bánh Mì Không - Beat Chuẩn || ĐạtG x DuUyên x QuangT",
        duration: 216,
        url: "https://youtube.com/watch?v=Jox18WfgTV8",
        thumbnail: "https://i.ytimg.com/vi/Jox18WfgTV8/hq720.jpg",
        author: "QuangT Official",
      },
      {
        video_id: "q9J-dM_fSUs",
        title: "[KARAOKE SONG CA] - ĐỪNG NHƯ THÓI QUEN - Jaykii ft Sara Lưu",
        duration: 275,
        url: "https://youtube.com/watch?v=q9J-dM_fSUs",
        thumbnail: "https://i.ytimg.com/vi/q9J-dM_fSUs/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "m8qN8a5kNJ0",
        title:
          "Sài Gòn Đau Lòng Quá Karaoke Tone Nữ | Hứa Kim Tuyền | Tuấn Lê Piano",
        duration: 308,
        url: "https://youtube.com/watch?v=m8qN8a5kNJ0",
        thumbnail: "https://i.ytimg.com/vi/m8qN8a5kNJ0/hq720.jpg",
        author: "Tuấn Lê Piano",
      },
      {
        video_id: "yP27mIX5nh4",
        title: "[KARAOKE SONG CA] KHÓ VẼ NỤ CƯỜI - ĐẠTG x DU UYÊN | BEAT CHUẨN",
        duration: 319,
        url: "https://youtube.com/watch?v=yP27mIX5nh4",
        thumbnail: "https://i.ytimg.com/vi/yP27mIX5nh4/hq720.jpg",
        author: "Internity",
      },
      {
        video_id: "IpSeS7bdOa4",
        title:
          "[KARAOKE SONG CA] - NƠI TÌNH YÊU BẮT ĐẦU - Bằng Kiều ft Lam Anh",
        duration: 282,
        url: "https://youtube.com/watch?v=IpSeS7bdOa4",
        thumbnail: "https://i.ytimg.com/vi/IpSeS7bdOa4/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "SsLiKrTTcwo",
        title: "Karaoke Yêu Một Người Có Lẽ   Miu Lê ft  Lou Hoàng Beat",
        duration: 251,
        url: "https://youtube.com/watch?v=SsLiKrTTcwo",
        thumbnail: "https://i.ytimg.com/vi/SsLiKrTTcwo/hq720.jpg",
        author: "thuong hieu vuive channel",
      },
      {
        video_id: "qNbXYIVhqoo",
        title: "[KARAOKE] KHI EM LỚN _Orange x Hoàng Dũng - Beat chuẩn (maN)",
        duration: 228,
        url: "https://youtube.com/watch?v=qNbXYIVhqoo",
        thumbnail: "https://i.ytimg.com/vi/qNbXYIVhqoo/hq720.jpg",
        author: "Nguyễn Hà Nam",
      },
      {
        video_id: "oUUT0cPsJQc",
        title:
          "KHÁC BIỆT TO LỚN (OFFICIAL KARAOKE) | TRỊNH THĂNG BÌNH - LIZ KIM CƯƠNG |",
        duration: 250,
        url: "https://youtube.com/watch?v=oUUT0cPsJQc",
        thumbnail: "https://i.ytimg.com/vi/oUUT0cPsJQc/hq720.jpg",
        author: "PLAN B",
      },
      {
        video_id: "whv4DdSLMCU",
        title: "SÀI GÒN HÔM NAY MƯA - JSOL & HOÀNG DUYÊN | Karaoke Version",
        duration: 248,
        url: "https://youtube.com/watch?v=whv4DdSLMCU",
        thumbnail: "https://i.ytimg.com/vi/whv4DdSLMCU/hq720.jpg",
        author: "DreamS Entertainment",
      },
      {
        video_id: "DpuPTjEGxms",
        title:
          "TĂNG DUY TÂN & HÒA MINZY - BẬT TÌNH YÊU LÊN - KARAOKE  | BEAT CHUẨN CÓ AD LIB | icT Sound",
        duration: 201,
        url: "https://youtube.com/watch?v=DpuPTjEGxms",
        thumbnail: "https://i.ytimg.com/vi/DpuPTjEGxms/hq720.jpg",
        author: "icT Sound",
      },
    ],
  },
  {
    id: CategoriesId.SONG_CA,
    name: "Song Ca",
    image: categoryImages[CategoriesId.SONG_CA],
    videos: [
      {
        video_id: "IpSeS7bdOa4",
        title:
          "[KARAOKE SONG CA] - NƠI TÌNH YÊU BẮT ĐẦU - Bằng Kiều ft Lam Anh",
        duration: 282,
        url: "https://youtube.com/watch?v=IpSeS7bdOa4",
        thumbnail: "https://i.ytimg.com/vi/IpSeS7bdOa4/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "MJVfZACz68A",
        title:
          "KARAOKE | Ngày Ta Có Nhau - LyLy x Anh Tú | Khắc Hưng | PNJ | Y T KALAKOLE",
        duration: 391,
        url: "https://youtube.com/watch?v=MJVfZACz68A",
        thumbnail: "https://i.ytimg.com/vi/MJVfZACz68A/hq720.jpg",
        author: "Y T KALAKOLE",
      },
      {
        video_id: "VrWFRJcIi1I",
        title: "Đừng Xin Lỗi Nữa Karaoke   Min/Erik  Beat Gốc",
        duration: 230,
        url: "https://youtube.com/watch?v=VrWFRJcIi1I",
        thumbnail: "https://i.ytimg.com/vi/VrWFRJcIi1I/hq720.jpg",
        author: "Ngô Tuệ",
      },
      {
        video_id: "deB8vpbmf5M",
        title:
          "Say Yes - OgeNus và PiaLinh | Chọn Gì? Chọn ĐI! | OFFICIAL KARAOKE",
        duration: 222,
        url: "https://youtube.com/watch?v=deB8vpbmf5M",
        thumbnail: "https://i.ytimg.com/vi/deB8vpbmf5M/hq720.jpg",
        author: "Chọn Gì? Chọn ĐI!",
      },
      {
        video_id: "RrfVTPWBBDs",
        title: "Vì Mẹ Anh Bắt Chia Tay - Karaoke Nguyên Bản | MGR",
        duration: 265,
        url: "https://youtube.com/watch?v=RrfVTPWBBDs",
        thumbnail: "https://i.ytimg.com/vi/RrfVTPWBBDs/hq720.jpg",
        author: "MGR KARAOKE",
      },
      {
        video_id: "g5swLzGGjEs",
        title:
          "Gặp Nhưng Không Ở Lại - Karaoke Tone Nữ Chuẩn | Hiền Hồ Ft. Vương Anh Tú",
        duration: 282,
        url: "https://youtube.com/watch?v=g5swLzGGjEs",
        thumbnail: "https://i.ytimg.com/vi/g5swLzGGjEs/hq720.jpg",
        author: "Hiền Hồ Official",
      },
      {
        video_id: "p5R7jTdCCVY",
        title:
          "[Karaoke] Tình Yêu Màu Nắng  Bigdaddy ft Đoàn Thúy Trang Full (BEAT CHUẨN)",
        duration: 304,
        url: "https://youtube.com/watch?v=p5R7jTdCCVY",
        thumbnail: "https://i.ytimg.com/vi/p5R7jTdCCVY/hq720.jpg",
        author: "Trịnh Đức Anh",
      },
      {
        video_id: "KuG7JC449AE",
        title:
          "Karaoke | Đếm Ngày Xa Em - Only C ft. Lou Hoàng (BEAT HẠ 1.5 TONE)",
        duration: 256,
        url: "https://youtube.com/watch?v=KuG7JC449AE",
        thumbnail: "https://i.ytimg.com/vi/KuG7JC449AE/hq720.jpg",
        author: "NMT",
      },
      {
        video_id: "GAc_G1tonwg",
        title:
          "[ KARAOKE BEAT CHUẨN ] BẮC BLING ( BẮC NINH ) - HOÀ MINZY FT NS XUÂN HINH x MASEW x TUẤN CRY",
        duration: 259,
        url: "https://youtube.com/watch?v=GAc_G1tonwg",
        thumbnail: "https://i.ytimg.com/vi/GAc_G1tonwg/hq720.jpg",
        author: "Hòa Minzy",
      },
      {
        video_id: "_O_m_kkHLj8",
        title: "Xin Anh Đừng - Emily ft. Lil' Knight.JustaTee ( karaoke )",
        duration: 207,
        url: "https://youtube.com/watch?v=_O_m_kkHLj8",
        thumbnail: "https://i.ytimg.com/vi/_O_m_kkHLj8/hq720.jpg",
        author: "Hà Bùi Thị",
      },
      {
        video_id: "q8mFT5qTegg",
        title:
          "Beat Chuẩn - BẠN ĐỜI - KARIK - (FT. GDUCKY) - KARAOKE CHUẨN DỄ HÁT",
        duration: 273,
        url: "https://youtube.com/watch?v=q8mFT5qTegg",
        thumbnail: "https://i.ytimg.com/vi/q8mFT5qTegg/hq720.jpg",
        author: "Karaoke Beat Gốc",
      },
      {
        video_id: "qNbXYIVhqoo",
        title: "[KARAOKE] KHI EM LỚN _Orange x Hoàng Dũng - Beat chuẩn (maN)",
        duration: 228,
        url: "https://youtube.com/watch?v=qNbXYIVhqoo",
        thumbnail: "https://i.ytimg.com/vi/qNbXYIVhqoo/hq720.jpg",
        author: "Nguyễn Hà Nam",
      },
      {
        video_id: "4dfGHeoMvqs",
        title:
          "[KARAOKE BEAT GỐC] MƯA THÁNG SÁU - VĂN MAI HƯƠNG ft. GREY D, TRUNG QUÂN (Prod. by HỨA KIM TUYỀN)",
        duration: 258,
        url: "https://youtube.com/watch?v=4dfGHeoMvqs",
        thumbnail: "https://i.ytimg.com/vi/4dfGHeoMvqs/hq720.jpg",
        author: "VĂN MAI HƯƠNG OFFICIAL",
      },
      {
        video_id: "15swO2LRcG4",
        title:
          "[KARAOKE] để tôi ôm em bằng giai điệu này - KAI ĐINH x MIN x GREY D | Instrumental/ Lofi Beat",
        duration: 265,
        url: "https://youtube.com/watch?v=15swO2LRcG4",
        thumbnail: "https://i.ytimg.com/vi/15swO2LRcG4/hq720.jpg",
        author: "Kai Dinh Official",
      },
      {
        video_id: "FDdqvu0dpH8",
        title:
          "Cơn Mưa Tình Yêu - Karaoke - Song Ca - Hà Anh Tuấn ft Phương Linh",
        duration: 292,
        url: "https://youtube.com/watch?v=FDdqvu0dpH8",
        thumbnail: "https://i.ytimg.com/vi/FDdqvu0dpH8/hq720.jpg",
        author: "Yeah ! Smile",
      },
      {
        video_id: "iUvEFK5W-JA",
        title: "[Karaoke] Thiên Đường Gọi Tên beat Hà An Huy và Phương Linh",
        duration: 250,
        url: "https://youtube.com/watch?v=iUvEFK5W-JA",
        thumbnail: "https://i.ytimg.com/vi/iUvEFK5W-JA/hq720.jpg",
        author: "Mê Hát",
      },
      {
        video_id: "sYzdTm2cxOE",
        title:
          "Anh Đánh Rơi Người Yêu Này - Andiez ft. AMEE | Karaoke Beat Chuẩn",
        duration: 208,
        url: "https://youtube.com/watch?v=sYzdTm2cxOE",
        thumbnail: "https://i.ytimg.com/vi/sYzdTm2cxOE/hq720.jpg",
        author: "Minh Hiếu Official",
      },
      {
        video_id: "q0ALJx-XM5M",
        title: "Karaoke Ngày Hạnh Phúc Hồ Ngọc Hà ft nhóm VMusic",
        duration: 311,
        url: "https://youtube.com/watch?v=q0ALJx-XM5M",
        thumbnail: "https://i.ytimg.com/vi/q0ALJx-XM5M/hq720.jpg",
        author: "Chin Anh",
      },
      {
        video_id: "z8dFh7vJoPY",
        title: "KARAOKE _ QUA ĐÊM NAY _ Phương Linh và Hà Anh Tuấn beat chuẩn",
        duration: 295,
        url: "https://youtube.com/watch?v=z8dFh7vJoPY",
        thumbnail: "https://i.ytimg.com/vi/z8dFh7vJoPY/hq720.jpg",
        author: "I'm Trinh",
      },
      {
        video_id: "q_1Vckcsz70",
        title:
          "Karaoke | Thời Thanh Xuân Sẽ Qua - Orange ft. Phạm Hồng Phước (XHTĐRLX) Beat Tách  ✅",
        duration: 257,
        url: "https://youtube.com/watch?v=q_1Vckcsz70",
        thumbnail: "https://i.ytimg.com/vi/q_1Vckcsz70/hq720.jpg",
        author: "Dương Trung KTV",
      },
      {
        video_id: "l5rtRuxUJ7o",
        title:
          "Mượn Rượu Tỏ Tình Beat Chuẩn   Karaoke Beat Chuẩn   BigDaddy Ft Emily",
        duration: 226,
        url: "https://youtube.com/watch?v=l5rtRuxUJ7o",
        thumbnail: "https://i.ytimg.com/vi/l5rtRuxUJ7o/hq720.jpg",
        author: "Music Karaoke (Melody)",
      },
      {
        video_id: "SsLiKrTTcwo",
        title: "Karaoke Yêu Một Người Có Lẽ   Miu Lê ft  Lou Hoàng Beat",
        duration: 251,
        url: "https://youtube.com/watch?v=SsLiKrTTcwo",
        thumbnail: "https://i.ytimg.com/vi/SsLiKrTTcwo/hq720.jpg",
        author: "thuong hieu vuive channel",
      },
      {
        video_id: "eFnvhFpM2pA",
        title: "TA LÀ CỦA NHAU KARAOKE ( BEAT CHUẨN )",
        duration: 179,
        url: "https://youtube.com/watch?v=eFnvhFpM2pA",
        thumbnail: "https://i.ytimg.com/vi/eFnvhFpM2pA/hq720.jpg",
        author: "NEIL HÀ OFFICIAL",
      },
      {
        video_id: "iFW_nq78INI",
        title: "AMEE x B RAY - Anh Nhà Ở Đâu Thế  Karaoke [Beat Chuẩn]",
        duration: 219,
        url: "https://youtube.com/watch?v=iFW_nq78INI",
        thumbnail: "https://i.ytimg.com/vi/iFW_nq78INI/hq720.jpg",
        author: "Best MusicMix",
      },
      {
        video_id: "Qu9cT38Cjds",
        title:
          "KARAOKE Cưới Nhau Đi (Beat Chuẩn không bè)  Yes I Do - Bùi Anh Tuấn if Hiền Hồ",
        duration: 263,
        url: "https://youtube.com/watch?v=Qu9cT38Cjds",
        thumbnail: "https://i.ytimg.com/vi/Qu9cT38Cjds/hq720.jpg",
        author: "Hoàng Nhật",
      },
      {
        video_id: "5nwYi1mxNVI",
        title:
          "KARAOKE| CHỈ LÀ KHÔNG CÙNG NHAU (Nhạc Hoa Lời Việt) | TĂNG PHÚC ft TRƯƠNG THẢO NHI | BEAT CHUẨN",
        duration: 235,
        url: "https://youtube.com/watch?v=5nwYi1mxNVI",
        thumbnail: "https://i.ytimg.com/vi/5nwYi1mxNVI/hq720.jpg",
        author: "TĂNG PHÚC OFFICIAL",
      },
      {
        video_id: "NVV2ysFeaPo",
        title:
          "[Karaoke] Bốn Chữ Lắm - Trúc Nhân ft. Trương Thảo Nhi [Song Ca]",
        duration: 260,
        url: "https://youtube.com/watch?v=NVV2ysFeaPo",
        thumbnail: "https://i.ytimg.com/vi/NVV2ysFeaPo/hq720.jpg",
        author: "Tài Nguyễn",
      },
      {
        video_id: "Wr9Xh3pzmUI",
        title: "[Karaoke] Tình về nơi đâu Full_Ken.Wasabi",
        duration: 250,
        url: "https://youtube.com/watch?v=Wr9Xh3pzmUI",
        thumbnail: "https://i.ytimg.com/vi/Wr9Xh3pzmUI/hqdefault.jpg",
        author: "kenny hpu",
      },
      {
        video_id: "qCjkN9iXBcc",
        title: "KARAOKE BEAT NGÀY MAI EM ĐI 2017   LÊ HIẾU ft SOOBIN HOÀNG SƠN",
        duration: 219,
        url: "https://youtube.com/watch?v=qCjkN9iXBcc",
        thumbnail: "https://i.ytimg.com/vi/qCjkN9iXBcc/hq720.jpg",
        author: "PDL Event",
      },
      {
        video_id: "LlkX6gcZy6A",
        title: "[Karaoke] Tình Yêu Ngủ Quên - Hoàng Tôn ft LyHan",
        duration: 188,
        url: "https://youtube.com/watch?v=LlkX6gcZy6A",
        thumbnail: "https://i.ytimg.com/vi/LlkX6gcZy6A/hqdefault.jpg",
        author: "QuyenAnh HD Official",
      },
      {
        video_id: "WpuLgWJcqrs",
        title:
          "Karaoke Nỗi Nhớ Đầy Vơi (Beat Gốc Bè) - Noo Phước Thịnh ft Hồ Ngọc Hà",
        duration: 306,
        url: "https://youtube.com/watch?v=WpuLgWJcqrs",
        thumbnail: "https://i.ytimg.com/vi/WpuLgWJcqrs/hq720.jpg",
        author: "N KTV",
      },
      {
        video_id: "CMVu3j5GznE",
        title: "[Karaoke] Mùa ta đã yêu-Hồng Phước Idol,Hương Giang Idol",
        duration: 229,
        url: "https://youtube.com/watch?v=CMVu3j5GznE",
        thumbnail: "https://i.ytimg.com/vi/CMVu3j5GznE/hqdefault.jpg",
        author: "kiên lê",
      },
      {
        video_id: "8vD-4doSzDs",
        title:
          "[KARAOKE] EX'S HATE ME (PART 2) - AMEE x B RAY | Instrumental/Beat Gốc (Tone Nữ)",
        duration: 217,
        url: "https://youtube.com/watch?v=8vD-4doSzDs",
        thumbnail: "https://i.ytimg.com/vi/8vD-4doSzDs/hq720.jpg",
        author: "AMEE",
      },
      {
        video_id: "Kgn2AErRfZQ",
        title: "Gác lại âu lo - Da LAB ft. Miu Lê (Official Karaoke Video)",
        duration: 307,
        url: "https://youtube.com/watch?v=Kgn2AErRfZQ",
        thumbnail: "https://i.ytimg.com/vi/Kgn2AErRfZQ/hq720.jpg",
        author: "Da LAB Official",
      },
      {
        video_id: "u62xH5MlRX8",
        title: "[Karaoke] Người Lạ Ơi",
        duration: 218,
        url: "https://youtube.com/watch?v=u62xH5MlRX8",
        thumbnail: "https://i.ytimg.com/vi/u62xH5MlRX8/hq720.jpg",
        author: "Thing",
      },
      {
        video_id: "76YTAIkq3NU",
        title:
          "KARAOKE | Ngôi Nhà Hoa Hồng - Quang Vinh x Bảo Thy | Beat phối mới chuẩn TONE GỐC ( Tone G - B )",
        duration: 340,
        url: "https://youtube.com/watch?v=76YTAIkq3NU",
        thumbnail: "https://i.ytimg.com/vi/76YTAIkq3NU/hq720.jpg",
        author: "Sang Bùi Studio OFFICIAL",
      },
      {
        video_id: "kAIuVahi9wU",
        title: "Karaoke Một Vòng Trái Đất ( Song Ca )",
        duration: 262,
        url: "https://youtube.com/watch?v=kAIuVahi9wU",
        thumbnail: "https://i.ytimg.com/vi/kAIuVahi9wU/hq720.jpg",
        author: "Tiên Over",
      },
      {
        video_id: "QRwlhPUcc50",
        title: "Karaoke Thu Cuối - Yanbi ft Mr T, Hằng Bing Boong full beat",
        duration: 287,
        url: "https://youtube.com/watch?v=QRwlhPUcc50",
        thumbnail: "https://i.ytimg.com/vi/QRwlhPUcc50/hq720.jpg",
        author: "Anh Nguyễn Đình",
      },
      {
        video_id: "DcETDzRvPmg",
        title: "KARAOKE Xe đạp - Thùy Chi M4U",
        duration: 286,
        url: "https://youtube.com/watch?v=DcETDzRvPmg",
        thumbnail: "https://i.ytimg.com/vi/DcETDzRvPmg/hq720.jpg",
        author: "Karaoke Việt HD",
      },
      {
        video_id: "fBrJ_x9CznU",
        title: "[Karaoke-TDP] Từng ngày anh mơ về em",
        duration: 207,
        url: "https://youtube.com/watch?v=fBrJ_x9CznU",
        thumbnail: "https://i.ytimg.com/vi/fBrJ_x9CznU/hqdefault.jpg",
        author: "TDP Dipain",
      },
      {
        video_id: "w7EGe320XU8",
        title:
          "[ Karaoke Song Ca ] Tận Cùng Nỗi Nhớ - Will ft Hansara (Beat chuẩn)",
        duration: 287,
        url: "https://youtube.com/watch?v=w7EGe320XU8",
        thumbnail: "https://i.ytimg.com/vi/w7EGe320XU8/hq720.jpg",
        author: "Hồng Ân Karaoke",
      },
      {
        video_id: "-CvSREY1I10",
        title: "Chưa Bao giờ Mẹ Kể full beat karaoke Min; Erik",
        duration: 259,
        url: "https://youtube.com/watch?v=-CvSREY1I10",
        thumbnail: "https://i.ytimg.com/vi/-CvSREY1I10/hq720.jpg",
        author: "Hàng Nhật Bãi VLOG",
      },
      {
        video_id: "Jox18WfgTV8",
        title: "Karaoke Bánh Mì Không - Beat Chuẩn || ĐạtG x DuUyên x QuangT",
        duration: 216,
        url: "https://youtube.com/watch?v=Jox18WfgTV8",
        thumbnail: "https://i.ytimg.com/vi/Jox18WfgTV8/hq720.jpg",
        author: "QuangT Official",
      },
      {
        video_id: "q9J-dM_fSUs",
        title: "[KARAOKE SONG CA] - ĐỪNG NHƯ THÓI QUEN - Jaykii ft Sara Lưu",
        duration: 275,
        url: "https://youtube.com/watch?v=q9J-dM_fSUs",
        thumbnail: "https://i.ytimg.com/vi/q9J-dM_fSUs/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "m8qN8a5kNJ0",
        title:
          "Sài Gòn Đau Lòng Quá Karaoke Tone Nữ | Hứa Kim Tuyền | Tuấn Lê Piano",
        duration: 308,
        url: "https://youtube.com/watch?v=m8qN8a5kNJ0",
        thumbnail: "https://i.ytimg.com/vi/m8qN8a5kNJ0/hq720.jpg",
        author: "Tuấn Lê Piano",
      },
      {
        video_id: "yP27mIX5nh4",
        title: "[KARAOKE SONG CA] KHÓ VẼ NỤ CƯỜI - ĐẠTG x DU UYÊN | BEAT CHUẨN",
        duration: 319,
        url: "https://youtube.com/watch?v=yP27mIX5nh4",
        thumbnail: "https://i.ytimg.com/vi/yP27mIX5nh4/hq720.jpg",
        author: "Internity",
      },
      {
        video_id: "IpSeS7bdOa4",
        title:
          "[KARAOKE SONG CA] - NƠI TÌNH YÊU BẮT ĐẦU - Bằng Kiều ft Lam Anh",
        duration: 282,
        url: "https://youtube.com/watch?v=IpSeS7bdOa4",
        thumbnail: "https://i.ytimg.com/vi/IpSeS7bdOa4/hq720.jpg",
        author: "Yêu Ca Hát",
      },
      {
        video_id: "SsLiKrTTcwo",
        title: "Karaoke Yêu Một Người Có Lẽ   Miu Lê ft  Lou Hoàng Beat",
        duration: 251,
        url: "https://youtube.com/watch?v=SsLiKrTTcwo",
        thumbnail: "https://i.ytimg.com/vi/SsLiKrTTcwo/hq720.jpg",
        author: "thuong hieu vuive channel",
      },
      {
        video_id: "qNbXYIVhqoo",
        title: "[KARAOKE] KHI EM LỚN _Orange x Hoàng Dũng - Beat chuẩn (maN)",
        duration: 228,
        url: "https://youtube.com/watch?v=qNbXYIVhqoo",
        thumbnail: "https://i.ytimg.com/vi/qNbXYIVhqoo/hq720.jpg",
        author: "Nguyễn Hà Nam",
      },
      {
        video_id: "oUUT0cPsJQc",
        title:
          "KHÁC BIỆT TO LỚN (OFFICIAL KARAOKE) | TRỊNH THĂNG BÌNH - LIZ KIM CƯƠNG |",
        duration: 250,
        url: "https://youtube.com/watch?v=oUUT0cPsJQc",
        thumbnail: "https://i.ytimg.com/vi/oUUT0cPsJQc/hq720.jpg",
        author: "PLAN B",
      },
      {
        video_id: "whv4DdSLMCU",
        title: "SÀI GÒN HÔM NAY MƯA - JSOL & HOÀNG DUYÊN | Karaoke Version",
        duration: 248,
        url: "https://youtube.com/watch?v=whv4DdSLMCU",
        thumbnail: "https://i.ytimg.com/vi/whv4DdSLMCU/hq720.jpg",
        author: "DreamS Entertainment",
      },
      {
        video_id: "DpuPTjEGxms",
        title:
          "TĂNG DUY TÂN & HÒA MINZY - BẬT TÌNH YÊU LÊN - KARAOKE  | BEAT CHUẨN CÓ AD LIB | icT Sound",
        duration: 201,
        url: "https://youtube.com/watch?v=DpuPTjEGxms",
        thumbnail: "https://i.ytimg.com/vi/DpuPTjEGxms/hq720.jpg",
        author: "icT Sound",
      },
    ],
  },
];
